/*
Package openconfigacl is a generated package which contains definitions
of structs which generate gNMI paths for a YANG schema.

This package was generated by ygnmi version: v0.15.0: (ygot: v0.35.0)
using the following YANG input files:
	- ./yang-repo/openconfig/interfaces/openconfig-interfaces.yang
	- ./yang-repo/openconfig/interfaces/openconfig-if-ip.yang
	- ./yang-repo/openconfig/bgp/openconfig-bgp.yang
	- ./yang-repo/openconfig/acl/openconfig-acl.yang
	- ./yang-repo/openconfig/network-instance/openconfig-network-instance.yang
	- ./yang-repo/openconfig/system/openconfig-system.yang
Imported modules were sourced from:
	- ./yang-repo
	- ./yang-repo/iana
	- ./yang-repo/ietf
	- ./yang-repo/mappings
	- ./yang-repo/mappings/openconfig
	- ./yang-repo/openconfig
	- ./yang-repo/openconfig/acl
	- ./yang-repo/openconfig/aft
	- ./yang-repo/openconfig/bfd
	- ./yang-repo/openconfig/bgp
	- ./yang-repo/openconfig/defined-sets
	- ./yang-repo/openconfig/extensions
	- ./yang-repo/openconfig/flex-algo
	- ./yang-repo/openconfig/gnsi
	- ./yang-repo/openconfig/gribi
	- ./yang-repo/openconfig/interfaces
	- ./yang-repo/openconfig/isis
	- ./yang-repo/openconfig/keychain
	- ./yang-repo/openconfig/lacp
	- ./yang-repo/openconfig/lldp
	- ./yang-repo/openconfig/local-routing
	- ./yang-repo/openconfig/mpls
	- ./yang-repo/openconfig/multicast
	- ./yang-repo/openconfig/network-instance
	- ./yang-repo/openconfig/optical-transport
	- ./yang-repo/openconfig/ospf
	- ./yang-repo/openconfig/p4rt
	- ./yang-repo/openconfig/pcep
	- ./yang-repo/openconfig/platform
	- ./yang-repo/openconfig/policy-forwarding
	- ./yang-repo/openconfig/policy
	- ./yang-repo/openconfig/qos
	- ./yang-repo/openconfig/rib
	- ./yang-repo/openconfig/sampling
	- ./yang-repo/openconfig/segment-routing
	- ./yang-repo/openconfig/stp
	- ./yang-repo/openconfig/system
	- ./yang-repo/openconfig/test
	- ./yang-repo/openconfig/types
	- ./yang-repo/openconfig/vlan
	- ./yang-repo/srl_nokia
	- ./yang-repo/srl_nokia/models
	- ./yang-repo/srl_nokia/models/acl
	- ./yang-repo/srl_nokia/models/bfd
	- ./yang-repo/srl_nokia/models/common
	- ./yang-repo/srl_nokia/models/ethcfm
	- ./yang-repo/srl_nokia/models/grpc
	- ./yang-repo/srl_nokia/models/interfaces
	- ./yang-repo/srl_nokia/models/ndk
	- ./yang-repo/srl_nokia/models/network-instance
	- ./yang-repo/srl_nokia/models/oam
	- ./yang-repo/srl_nokia/models/platform
	- ./yang-repo/srl_nokia/models/qos
	- ./yang-repo/srl_nokia/models/routing-policy
	- ./yang-repo/srl_nokia/models/service-activation-testhead
	- ./yang-repo/srl_nokia/models/stp
	- ./yang-repo/srl_nokia/models/subscriber-mgmt
	- ./yang-repo/srl_nokia/models/sync
	- ./yang-repo/srl_nokia/models/system
	- ./yang-repo/srl_nokia/models/transport-security
	- ./yang-repo/srl_nokia/models/tunnel
	- ./yang-repo/srl_nokia/models/twamp
*/
package openconfigacl

import (
	"reflect"
	oc "github.com/LeBaoTai/SDN-RD/internal/oc"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygnmi/ygnmi"
	"github.com/openconfig/ygot/ytypes"
)

// Acl_AclSet_AclEntry_Mpls_TrafficClassPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/state/traffic-class YANG schema element.
type Acl_AclSet_AclEntry_Mpls_TrafficClassPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Mpls_TrafficClassPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/state/traffic-class YANG schema element.
type Acl_AclSet_AclEntry_Mpls_TrafficClassPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Mpls_TrafficClassPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/traffic-class"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/state/traffic-class"
func (n *Acl_AclSet_AclEntry_Mpls_TrafficClassPath) State() ygnmi.SingletonQuery[uint8] {
	return ygnmi.NewSingletonQuery[uint8](
		"Acl_AclSet_AclEntry_Mpls",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "traffic-class"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Mpls).TrafficClass
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Mpls) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/traffic-class"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/state/traffic-class"
func (n *Acl_AclSet_AclEntry_Mpls_TrafficClassPathAny) State() ygnmi.WildcardQuery[uint8] {
	return ygnmi.NewWildcardQuery[uint8](
		"Acl_AclSet_AclEntry_Mpls",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "traffic-class"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Mpls).TrafficClass
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Mpls) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/traffic-class"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/config/traffic-class"
func (n *Acl_AclSet_AclEntry_Mpls_TrafficClassPath) Config() ygnmi.ConfigQuery[uint8] {
	return ygnmi.NewConfigQuery[uint8](
		"Acl_AclSet_AclEntry_Mpls",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "traffic-class"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Mpls).TrafficClass
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Mpls) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/traffic-class"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/config/traffic-class"
func (n *Acl_AclSet_AclEntry_Mpls_TrafficClassPathAny) Config() ygnmi.WildcardQuery[uint8] {
	return ygnmi.NewWildcardQuery[uint8](
		"Acl_AclSet_AclEntry_Mpls",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "traffic-class"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Mpls).TrafficClass
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Mpls) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Mpls_TtlValuePath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/state/ttl-value YANG schema element.
type Acl_AclSet_AclEntry_Mpls_TtlValuePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Mpls_TtlValuePathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/state/ttl-value YANG schema element.
type Acl_AclSet_AclEntry_Mpls_TtlValuePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Mpls_TtlValuePath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/ttl-value"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/state/ttl-value"
func (n *Acl_AclSet_AclEntry_Mpls_TtlValuePath) State() ygnmi.SingletonQuery[uint8] {
	return ygnmi.NewSingletonQuery[uint8](
		"Acl_AclSet_AclEntry_Mpls",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "ttl-value"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Mpls).TtlValue
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Mpls) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/ttl-value"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/state/ttl-value"
func (n *Acl_AclSet_AclEntry_Mpls_TtlValuePathAny) State() ygnmi.WildcardQuery[uint8] {
	return ygnmi.NewWildcardQuery[uint8](
		"Acl_AclSet_AclEntry_Mpls",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "ttl-value"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Mpls).TtlValue
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Mpls) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/ttl-value"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/config/ttl-value"
func (n *Acl_AclSet_AclEntry_Mpls_TtlValuePath) Config() ygnmi.ConfigQuery[uint8] {
	return ygnmi.NewConfigQuery[uint8](
		"Acl_AclSet_AclEntry_Mpls",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "ttl-value"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Mpls).TtlValue
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Mpls) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/ttl-value"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/config/ttl-value"
func (n *Acl_AclSet_AclEntry_Mpls_TtlValuePathAny) Config() ygnmi.WildcardQuery[uint8] {
	return ygnmi.NewWildcardQuery[uint8](
		"Acl_AclSet_AclEntry_Mpls",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "ttl-value"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Mpls).TtlValue
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Mpls) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_MplsPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls YANG schema element.
type Acl_AclSet_AclEntry_MplsPath struct {
	*ygnmi.NodePath
}

// Acl_AclSet_AclEntry_MplsPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls YANG schema element.
type Acl_AclSet_AclEntry_MplsPathAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_MplsPath) PathOriginName() string {
     return "openconfig"
}

// EndLabelValue (leaf): Match MPLS label value on the MPLS header.
// The usage of this field indicated the upper
// range value in the top of the stack.
// The range that is used is inclusive. The match that
// is done for a particular received pkt_label is:
// start-label-value <= pkt_label <= end-label-value.
// The 20-bit label value in an MPLS label
// stack as specified in RFC 3032.
// This label value does not include the
// encodings of Traffic Class and TTL.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/end-label-value"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/*/end-label-value"
func (n *Acl_AclSet_AclEntry_MplsPath) EndLabelValue() *Acl_AclSet_AclEntry_Mpls_EndLabelValuePath {
	ps := &Acl_AclSet_AclEntry_Mpls_EndLabelValuePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "end-label-value"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// EndLabelValue (leaf): Match MPLS label value on the MPLS header.
// The usage of this field indicated the upper
// range value in the top of the stack.
// The range that is used is inclusive. The match that
// is done for a particular received pkt_label is:
// start-label-value <= pkt_label <= end-label-value.
// The 20-bit label value in an MPLS label
// stack as specified in RFC 3032.
// This label value does not include the
// encodings of Traffic Class and TTL.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/end-label-value"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/*/end-label-value"
func (n *Acl_AclSet_AclEntry_MplsPathAny) EndLabelValue() *Acl_AclSet_AclEntry_Mpls_EndLabelValuePathAny {
	ps := &Acl_AclSet_AclEntry_Mpls_EndLabelValuePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "end-label-value"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// StartLabelValue (leaf): Match MPLS label value on the MPLS header.
// The usage of this field indicated the upper
// range value in the top of the stack.
// The range that is used is inclusive. The match that
// is done for a particular received pkt_label is:
// start-label-value <= pkt_label <= end-label-value.
// The 20-bit label value in an MPLS label
// stack as specified in RFC 3032.
// This label value does not include the
// encodings of Traffic Class and TTL.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/start-label-value"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/*/start-label-value"
func (n *Acl_AclSet_AclEntry_MplsPath) StartLabelValue() *Acl_AclSet_AclEntry_Mpls_StartLabelValuePath {
	ps := &Acl_AclSet_AclEntry_Mpls_StartLabelValuePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "start-label-value"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// StartLabelValue (leaf): Match MPLS label value on the MPLS header.
// The usage of this field indicated the upper
// range value in the top of the stack.
// The range that is used is inclusive. The match that
// is done for a particular received pkt_label is:
// start-label-value <= pkt_label <= end-label-value.
// The 20-bit label value in an MPLS label
// stack as specified in RFC 3032.
// This label value does not include the
// encodings of Traffic Class and TTL.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/start-label-value"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/*/start-label-value"
func (n *Acl_AclSet_AclEntry_MplsPathAny) StartLabelValue() *Acl_AclSet_AclEntry_Mpls_StartLabelValuePathAny {
	ps := &Acl_AclSet_AclEntry_Mpls_StartLabelValuePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "start-label-value"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// TrafficClass (leaf): The value of the MPLS traffic class (TC) bits,
// formerly known as the EXP bits.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/traffic-class"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/*/traffic-class"
func (n *Acl_AclSet_AclEntry_MplsPath) TrafficClass() *Acl_AclSet_AclEntry_Mpls_TrafficClassPath {
	ps := &Acl_AclSet_AclEntry_Mpls_TrafficClassPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "traffic-class"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// TrafficClass (leaf): The value of the MPLS traffic class (TC) bits,
// formerly known as the EXP bits.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/traffic-class"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/*/traffic-class"
func (n *Acl_AclSet_AclEntry_MplsPathAny) TrafficClass() *Acl_AclSet_AclEntry_Mpls_TrafficClassPathAny {
	ps := &Acl_AclSet_AclEntry_Mpls_TrafficClassPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "traffic-class"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// TtlValue (leaf): Time-to-live MPLS packet value match.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/ttl-value"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/*/ttl-value"
func (n *Acl_AclSet_AclEntry_MplsPath) TtlValue() *Acl_AclSet_AclEntry_Mpls_TtlValuePath {
	ps := &Acl_AclSet_AclEntry_Mpls_TtlValuePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "ttl-value"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// TtlValue (leaf): Time-to-live MPLS packet value match.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/ttl-value"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/mpls/*/ttl-value"
func (n *Acl_AclSet_AclEntry_MplsPathAny) TtlValue() *Acl_AclSet_AclEntry_Mpls_TtlValuePathAny {
	ps := &Acl_AclSet_AclEntry_Mpls_TtlValuePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "ttl-value"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_AclSet_AclEntry_MplsPath) State() ygnmi.SingletonQuery[*oc.Acl_AclSet_AclEntry_Mpls] {
	return ygnmi.NewSingletonQuery[*oc.Acl_AclSet_AclEntry_Mpls](
		"Acl_AclSet_AclEntry_Mpls",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_AclSet_AclEntry_MplsPathAny) State() ygnmi.WildcardQuery[*oc.Acl_AclSet_AclEntry_Mpls] {
	return ygnmi.NewWildcardQuery[*oc.Acl_AclSet_AclEntry_Mpls](
		"Acl_AclSet_AclEntry_Mpls",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *Acl_AclSet_AclEntry_MplsPath) Config() ygnmi.ConfigQuery[*oc.Acl_AclSet_AclEntry_Mpls] {
	return ygnmi.NewConfigQuery[*oc.Acl_AclSet_AclEntry_Mpls](
		"Acl_AclSet_AclEntry_Mpls",
		false,
		true,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *Acl_AclSet_AclEntry_MplsPathAny) Config() ygnmi.WildcardQuery[*oc.Acl_AclSet_AclEntry_Mpls] {
	return ygnmi.NewWildcardQuery[*oc.Acl_AclSet_AclEntry_Mpls](
		"Acl_AclSet_AclEntry_Mpls",
		false,
		true,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Transport_BuiltinDetailPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/builtin-detail YANG schema element.
type Acl_AclSet_AclEntry_Transport_BuiltinDetailPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Transport_BuiltinDetailPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/builtin-detail YANG schema element.
type Acl_AclSet_AclEntry_Transport_BuiltinDetailPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Transport_BuiltinDetailPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/builtin-detail"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/builtin-detail"
func (n *Acl_AclSet_AclEntry_Transport_BuiltinDetailPath) State() ygnmi.SingletonQuery[oc.E_Transport_BuiltinDetail] {
	return ygnmi.NewSingletonQuery[oc.E_Transport_BuiltinDetail](
		"Acl_AclSet_AclEntry_Transport",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "builtin-detail"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Transport_BuiltinDetail, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).BuiltinDetail
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/builtin-detail"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/builtin-detail"
func (n *Acl_AclSet_AclEntry_Transport_BuiltinDetailPathAny) State() ygnmi.WildcardQuery[oc.E_Transport_BuiltinDetail] {
	return ygnmi.NewWildcardQuery[oc.E_Transport_BuiltinDetail](
		"Acl_AclSet_AclEntry_Transport",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "builtin-detail"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Transport_BuiltinDetail, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).BuiltinDetail
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/builtin-detail"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/config/builtin-detail"
func (n *Acl_AclSet_AclEntry_Transport_BuiltinDetailPath) Config() ygnmi.ConfigQuery[oc.E_Transport_BuiltinDetail] {
	return ygnmi.NewConfigQuery[oc.E_Transport_BuiltinDetail](
		"Acl_AclSet_AclEntry_Transport",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "builtin-detail"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Transport_BuiltinDetail, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).BuiltinDetail
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/builtin-detail"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/config/builtin-detail"
func (n *Acl_AclSet_AclEntry_Transport_BuiltinDetailPathAny) Config() ygnmi.WildcardQuery[oc.E_Transport_BuiltinDetail] {
	return ygnmi.NewWildcardQuery[oc.E_Transport_BuiltinDetail](
		"Acl_AclSet_AclEntry_Transport",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "builtin-detail"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Transport_BuiltinDetail, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).BuiltinDetail
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Transport_DestinationPortPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/destination-port YANG schema element.
type Acl_AclSet_AclEntry_Transport_DestinationPortPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Transport_DestinationPortPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/destination-port YANG schema element.
type Acl_AclSet_AclEntry_Transport_DestinationPortPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Transport_DestinationPortPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/destination-port"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/destination-port"
func (n *Acl_AclSet_AclEntry_Transport_DestinationPortPath) State() ygnmi.SingletonQuery[oc.Acl_AclSet_AclEntry_Transport_DestinationPort_Union] {
	return ygnmi.NewSingletonQuery[oc.Acl_AclSet_AclEntry_Transport_DestinationPort_Union](
		"Acl_AclSet_AclEntry_Transport",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "destination-port"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.Acl_AclSet_AclEntry_Transport_DestinationPort_Union, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).DestinationPort
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/destination-port"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/destination-port"
func (n *Acl_AclSet_AclEntry_Transport_DestinationPortPathAny) State() ygnmi.WildcardQuery[oc.Acl_AclSet_AclEntry_Transport_DestinationPort_Union] {
	return ygnmi.NewWildcardQuery[oc.Acl_AclSet_AclEntry_Transport_DestinationPort_Union](
		"Acl_AclSet_AclEntry_Transport",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "destination-port"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.Acl_AclSet_AclEntry_Transport_DestinationPort_Union, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).DestinationPort
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/destination-port"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/config/destination-port"
func (n *Acl_AclSet_AclEntry_Transport_DestinationPortPath) Config() ygnmi.ConfigQuery[oc.Acl_AclSet_AclEntry_Transport_DestinationPort_Union] {
	return ygnmi.NewConfigQuery[oc.Acl_AclSet_AclEntry_Transport_DestinationPort_Union](
		"Acl_AclSet_AclEntry_Transport",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "destination-port"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.Acl_AclSet_AclEntry_Transport_DestinationPort_Union, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).DestinationPort
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/destination-port"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/config/destination-port"
func (n *Acl_AclSet_AclEntry_Transport_DestinationPortPathAny) Config() ygnmi.WildcardQuery[oc.Acl_AclSet_AclEntry_Transport_DestinationPort_Union] {
	return ygnmi.NewWildcardQuery[oc.Acl_AclSet_AclEntry_Transport_DestinationPort_Union](
		"Acl_AclSet_AclEntry_Transport",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "destination-port"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.Acl_AclSet_AclEntry_Transport_DestinationPort_Union, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).DestinationPort
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Transport_DestinationPortSetPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/destination-port-set YANG schema element.
type Acl_AclSet_AclEntry_Transport_DestinationPortSetPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Transport_DestinationPortSetPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/destination-port-set YANG schema element.
type Acl_AclSet_AclEntry_Transport_DestinationPortSetPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Transport_DestinationPortSetPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/destination-port-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/destination-port-set"
func (n *Acl_AclSet_AclEntry_Transport_DestinationPortSetPath) State() ygnmi.SingletonQuery[string] {
	return ygnmi.NewSingletonQuery[string](
		"Acl_AclSet_AclEntry_Transport",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "destination-port-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).DestinationPortSet
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/destination-port-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/destination-port-set"
func (n *Acl_AclSet_AclEntry_Transport_DestinationPortSetPathAny) State() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Acl_AclSet_AclEntry_Transport",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "destination-port-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).DestinationPortSet
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/destination-port-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/config/destination-port-set"
func (n *Acl_AclSet_AclEntry_Transport_DestinationPortSetPath) Config() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"Acl_AclSet_AclEntry_Transport",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "destination-port-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).DestinationPortSet
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/destination-port-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/config/destination-port-set"
func (n *Acl_AclSet_AclEntry_Transport_DestinationPortSetPathAny) Config() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Acl_AclSet_AclEntry_Transport",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "destination-port-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).DestinationPortSet
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Transport_DetailModePath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/detail-mode YANG schema element.
type Acl_AclSet_AclEntry_Transport_DetailModePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Transport_DetailModePathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/detail-mode YANG schema element.
type Acl_AclSet_AclEntry_Transport_DetailModePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Transport_DetailModePath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/detail-mode"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/detail-mode"
func (n *Acl_AclSet_AclEntry_Transport_DetailModePath) State() ygnmi.SingletonQuery[oc.E_Transport_DetailMode] {
	return ygnmi.NewSingletonQuery[oc.E_Transport_DetailMode](
		"Acl_AclSet_AclEntry_Transport",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "detail-mode"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Transport_DetailMode, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).DetailMode
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/detail-mode"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/detail-mode"
func (n *Acl_AclSet_AclEntry_Transport_DetailModePathAny) State() ygnmi.WildcardQuery[oc.E_Transport_DetailMode] {
	return ygnmi.NewWildcardQuery[oc.E_Transport_DetailMode](
		"Acl_AclSet_AclEntry_Transport",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "detail-mode"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Transport_DetailMode, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).DetailMode
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/detail-mode"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/config/detail-mode"
func (n *Acl_AclSet_AclEntry_Transport_DetailModePath) Config() ygnmi.ConfigQuery[oc.E_Transport_DetailMode] {
	return ygnmi.NewConfigQuery[oc.E_Transport_DetailMode](
		"Acl_AclSet_AclEntry_Transport",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "detail-mode"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Transport_DetailMode, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).DetailMode
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/detail-mode"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/config/detail-mode"
func (n *Acl_AclSet_AclEntry_Transport_DetailModePathAny) Config() ygnmi.WildcardQuery[oc.E_Transport_DetailMode] {
	return ygnmi.NewWildcardQuery[oc.E_Transport_DetailMode](
		"Acl_AclSet_AclEntry_Transport",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "detail-mode"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Transport_DetailMode, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).DetailMode
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Transport_ExplicitDetailMatchModePath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/explicit-detail-match-mode YANG schema element.
type Acl_AclSet_AclEntry_Transport_ExplicitDetailMatchModePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Transport_ExplicitDetailMatchModePathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/explicit-detail-match-mode YANG schema element.
type Acl_AclSet_AclEntry_Transport_ExplicitDetailMatchModePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Transport_ExplicitDetailMatchModePath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/explicit-detail-match-mode"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/explicit-detail-match-mode"
func (n *Acl_AclSet_AclEntry_Transport_ExplicitDetailMatchModePath) State() ygnmi.SingletonQuery[oc.E_Transport_ExplicitDetailMatchMode] {
	return ygnmi.NewSingletonQuery[oc.E_Transport_ExplicitDetailMatchMode](
		"Acl_AclSet_AclEntry_Transport",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "explicit-detail-match-mode"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Transport_ExplicitDetailMatchMode, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).ExplicitDetailMatchMode
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/explicit-detail-match-mode"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/explicit-detail-match-mode"
func (n *Acl_AclSet_AclEntry_Transport_ExplicitDetailMatchModePathAny) State() ygnmi.WildcardQuery[oc.E_Transport_ExplicitDetailMatchMode] {
	return ygnmi.NewWildcardQuery[oc.E_Transport_ExplicitDetailMatchMode](
		"Acl_AclSet_AclEntry_Transport",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "explicit-detail-match-mode"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Transport_ExplicitDetailMatchMode, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).ExplicitDetailMatchMode
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/explicit-detail-match-mode"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/config/explicit-detail-match-mode"
func (n *Acl_AclSet_AclEntry_Transport_ExplicitDetailMatchModePath) Config() ygnmi.ConfigQuery[oc.E_Transport_ExplicitDetailMatchMode] {
	return ygnmi.NewConfigQuery[oc.E_Transport_ExplicitDetailMatchMode](
		"Acl_AclSet_AclEntry_Transport",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "explicit-detail-match-mode"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Transport_ExplicitDetailMatchMode, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).ExplicitDetailMatchMode
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/explicit-detail-match-mode"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/config/explicit-detail-match-mode"
func (n *Acl_AclSet_AclEntry_Transport_ExplicitDetailMatchModePathAny) Config() ygnmi.WildcardQuery[oc.E_Transport_ExplicitDetailMatchMode] {
	return ygnmi.NewWildcardQuery[oc.E_Transport_ExplicitDetailMatchMode](
		"Acl_AclSet_AclEntry_Transport",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "explicit-detail-match-mode"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_Transport_ExplicitDetailMatchMode, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).ExplicitDetailMatchMode
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Transport_ExplicitTcpFlagsPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/explicit-tcp-flags YANG schema element.
type Acl_AclSet_AclEntry_Transport_ExplicitTcpFlagsPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Transport_ExplicitTcpFlagsPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/explicit-tcp-flags YANG schema element.
type Acl_AclSet_AclEntry_Transport_ExplicitTcpFlagsPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Transport_ExplicitTcpFlagsPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/explicit-tcp-flags"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/explicit-tcp-flags"
func (n *Acl_AclSet_AclEntry_Transport_ExplicitTcpFlagsPath) State() ygnmi.SingletonQuery[[]oc.E_OpenconfigPacketMatchTypes_TCP_FLAGS] {
	return ygnmi.NewSingletonQuery[[]oc.E_OpenconfigPacketMatchTypes_TCP_FLAGS](
		"Acl_AclSet_AclEntry_Transport",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "explicit-tcp-flags"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.E_OpenconfigPacketMatchTypes_TCP_FLAGS, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).ExplicitTcpFlags
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/explicit-tcp-flags"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/state/explicit-tcp-flags"
func (n *Acl_AclSet_AclEntry_Transport_ExplicitTcpFlagsPathAny) State() ygnmi.WildcardQuery[[]oc.E_OpenconfigPacketMatchTypes_TCP_FLAGS] {
	return ygnmi.NewWildcardQuery[[]oc.E_OpenconfigPacketMatchTypes_TCP_FLAGS](
		"Acl_AclSet_AclEntry_Transport",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "explicit-tcp-flags"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.E_OpenconfigPacketMatchTypes_TCP_FLAGS, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).ExplicitTcpFlags
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/explicit-tcp-flags"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/config/explicit-tcp-flags"
func (n *Acl_AclSet_AclEntry_Transport_ExplicitTcpFlagsPath) Config() ygnmi.ConfigQuery[[]oc.E_OpenconfigPacketMatchTypes_TCP_FLAGS] {
	return ygnmi.NewConfigQuery[[]oc.E_OpenconfigPacketMatchTypes_TCP_FLAGS](
		"Acl_AclSet_AclEntry_Transport",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "explicit-tcp-flags"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.E_OpenconfigPacketMatchTypes_TCP_FLAGS, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).ExplicitTcpFlags
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/explicit-tcp-flags"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/transport/config/explicit-tcp-flags"
func (n *Acl_AclSet_AclEntry_Transport_ExplicitTcpFlagsPathAny) Config() ygnmi.WildcardQuery[[]oc.E_OpenconfigPacketMatchTypes_TCP_FLAGS] {
	return ygnmi.NewWildcardQuery[[]oc.E_OpenconfigPacketMatchTypes_TCP_FLAGS](
		"Acl_AclSet_AclEntry_Transport",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "explicit-tcp-flags"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.E_OpenconfigPacketMatchTypes_TCP_FLAGS, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Transport).ExplicitTcpFlags
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Transport) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}
