/*
Package openconfigacl is a generated package which contains definitions
of structs which generate gNMI paths for a YANG schema.

This package was generated by ygnmi version: v0.15.0: (ygot: v0.35.0)
using the following YANG input files:
	- ./yang-repo/openconfig/interfaces/openconfig-interfaces.yang
	- ./yang-repo/openconfig/interfaces/openconfig-if-ip.yang
	- ./yang-repo/openconfig/bgp/openconfig-bgp.yang
	- ./yang-repo/openconfig/acl/openconfig-acl.yang
	- ./yang-repo/openconfig/network-instance/openconfig-network-instance.yang
	- ./yang-repo/openconfig/system/openconfig-system.yang
Imported modules were sourced from:
	- ./yang-repo
	- ./yang-repo/iana
	- ./yang-repo/ietf
	- ./yang-repo/mappings
	- ./yang-repo/mappings/openconfig
	- ./yang-repo/openconfig
	- ./yang-repo/openconfig/acl
	- ./yang-repo/openconfig/aft
	- ./yang-repo/openconfig/bfd
	- ./yang-repo/openconfig/bgp
	- ./yang-repo/openconfig/defined-sets
	- ./yang-repo/openconfig/extensions
	- ./yang-repo/openconfig/flex-algo
	- ./yang-repo/openconfig/gnsi
	- ./yang-repo/openconfig/gribi
	- ./yang-repo/openconfig/interfaces
	- ./yang-repo/openconfig/isis
	- ./yang-repo/openconfig/keychain
	- ./yang-repo/openconfig/lacp
	- ./yang-repo/openconfig/lldp
	- ./yang-repo/openconfig/local-routing
	- ./yang-repo/openconfig/mpls
	- ./yang-repo/openconfig/multicast
	- ./yang-repo/openconfig/network-instance
	- ./yang-repo/openconfig/optical-transport
	- ./yang-repo/openconfig/ospf
	- ./yang-repo/openconfig/p4rt
	- ./yang-repo/openconfig/pcep
	- ./yang-repo/openconfig/platform
	- ./yang-repo/openconfig/policy-forwarding
	- ./yang-repo/openconfig/policy
	- ./yang-repo/openconfig/qos
	- ./yang-repo/openconfig/rib
	- ./yang-repo/openconfig/sampling
	- ./yang-repo/openconfig/segment-routing
	- ./yang-repo/openconfig/stp
	- ./yang-repo/openconfig/system
	- ./yang-repo/openconfig/test
	- ./yang-repo/openconfig/types
	- ./yang-repo/openconfig/vlan
	- ./yang-repo/srl_nokia
	- ./yang-repo/srl_nokia/models
	- ./yang-repo/srl_nokia/models/acl
	- ./yang-repo/srl_nokia/models/bfd
	- ./yang-repo/srl_nokia/models/common
	- ./yang-repo/srl_nokia/models/ethcfm
	- ./yang-repo/srl_nokia/models/grpc
	- ./yang-repo/srl_nokia/models/interfaces
	- ./yang-repo/srl_nokia/models/ndk
	- ./yang-repo/srl_nokia/models/network-instance
	- ./yang-repo/srl_nokia/models/oam
	- ./yang-repo/srl_nokia/models/platform
	- ./yang-repo/srl_nokia/models/qos
	- ./yang-repo/srl_nokia/models/routing-policy
	- ./yang-repo/srl_nokia/models/service-activation-testhead
	- ./yang-repo/srl_nokia/models/stp
	- ./yang-repo/srl_nokia/models/subscriber-mgmt
	- ./yang-repo/srl_nokia/models/sync
	- ./yang-repo/srl_nokia/models/system
	- ./yang-repo/srl_nokia/models/transport-security
	- ./yang-repo/srl_nokia/models/tunnel
	- ./yang-repo/srl_nokia/models/twamp
*/
package openconfigacl

import (
	"reflect"
	oc "github.com/LeBaoTai/SDN-RD/internal/oc"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygnmi/ygnmi"
	"github.com/openconfig/ygot/ytypes"
)

// Acl_AclSet_AclEntry_Ipv4_DestinationAddressPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/destination-address YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_DestinationAddressPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Ipv4_DestinationAddressPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/destination-address YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_DestinationAddressPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Ipv4_DestinationAddressPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/destination-address"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/destination-address"
func (n *Acl_AclSet_AclEntry_Ipv4_DestinationAddressPath) State() ygnmi.SingletonQuery[string] {
	return ygnmi.NewSingletonQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "destination-address"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).DestinationAddress
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/destination-address"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/destination-address"
func (n *Acl_AclSet_AclEntry_Ipv4_DestinationAddressPathAny) State() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "destination-address"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).DestinationAddress
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/destination-address"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/destination-address"
func (n *Acl_AclSet_AclEntry_Ipv4_DestinationAddressPath) Config() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "destination-address"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).DestinationAddress
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/destination-address"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/destination-address"
func (n *Acl_AclSet_AclEntry_Ipv4_DestinationAddressPathAny) Config() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "destination-address"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).DestinationAddress
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Ipv4_DestinationAddressPrefixSetPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/destination-address-prefix-set YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_DestinationAddressPrefixSetPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Ipv4_DestinationAddressPrefixSetPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/destination-address-prefix-set YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_DestinationAddressPrefixSetPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Ipv4_DestinationAddressPrefixSetPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/destination-address-prefix-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/destination-address-prefix-set"
func (n *Acl_AclSet_AclEntry_Ipv4_DestinationAddressPrefixSetPath) State() ygnmi.SingletonQuery[string] {
	return ygnmi.NewSingletonQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "destination-address-prefix-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).DestinationAddressPrefixSet
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/destination-address-prefix-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/destination-address-prefix-set"
func (n *Acl_AclSet_AclEntry_Ipv4_DestinationAddressPrefixSetPathAny) State() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "destination-address-prefix-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).DestinationAddressPrefixSet
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/destination-address-prefix-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/destination-address-prefix-set"
func (n *Acl_AclSet_AclEntry_Ipv4_DestinationAddressPrefixSetPath) Config() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "destination-address-prefix-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).DestinationAddressPrefixSet
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/destination-address-prefix-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/destination-address-prefix-set"
func (n *Acl_AclSet_AclEntry_Ipv4_DestinationAddressPrefixSetPathAny) Config() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "destination-address-prefix-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).DestinationAddressPrefixSet
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Ipv4_DscpPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/dscp YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_DscpPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Ipv4_DscpPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/dscp YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_DscpPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Ipv4_DscpPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/dscp"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/dscp"
func (n *Acl_AclSet_AclEntry_Ipv4_DscpPath) State() ygnmi.SingletonQuery[uint8] {
	return ygnmi.NewSingletonQuery[uint8](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "dscp"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).Dscp
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/dscp"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/dscp"
func (n *Acl_AclSet_AclEntry_Ipv4_DscpPathAny) State() ygnmi.WildcardQuery[uint8] {
	return ygnmi.NewWildcardQuery[uint8](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "dscp"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).Dscp
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/dscp"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/dscp"
func (n *Acl_AclSet_AclEntry_Ipv4_DscpPath) Config() ygnmi.ConfigQuery[uint8] {
	return ygnmi.NewConfigQuery[uint8](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "dscp"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).Dscp
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/dscp"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/dscp"
func (n *Acl_AclSet_AclEntry_Ipv4_DscpPathAny) Config() ygnmi.WildcardQuery[uint8] {
	return ygnmi.NewWildcardQuery[uint8](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "dscp"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).Dscp
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Ipv4_DscpSetPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/dscp-set YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_DscpSetPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Ipv4_DscpSetPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/dscp-set YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_DscpSetPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Ipv4_DscpSetPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/dscp-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/dscp-set"
func (n *Acl_AclSet_AclEntry_Ipv4_DscpSetPath) State() ygnmi.SingletonQuery[[]uint8] {
	return ygnmi.NewSingletonQuery[[]uint8](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "dscp-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).DscpSet
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/dscp-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/dscp-set"
func (n *Acl_AclSet_AclEntry_Ipv4_DscpSetPathAny) State() ygnmi.WildcardQuery[[]uint8] {
	return ygnmi.NewWildcardQuery[[]uint8](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "dscp-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).DscpSet
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/dscp-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/dscp-set"
func (n *Acl_AclSet_AclEntry_Ipv4_DscpSetPath) Config() ygnmi.ConfigQuery[[]uint8] {
	return ygnmi.NewConfigQuery[[]uint8](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "dscp-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).DscpSet
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/dscp-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/dscp-set"
func (n *Acl_AclSet_AclEntry_Ipv4_DscpSetPathAny) Config() ygnmi.WildcardQuery[[]uint8] {
	return ygnmi.NewWildcardQuery[[]uint8](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "dscp-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).DscpSet
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Ipv4_HopLimitPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/hop-limit YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_HopLimitPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Ipv4_HopLimitPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/hop-limit YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_HopLimitPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Ipv4_HopLimitPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/hop-limit"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/hop-limit"
func (n *Acl_AclSet_AclEntry_Ipv4_HopLimitPath) State() ygnmi.SingletonQuery[uint8] {
	return ygnmi.NewSingletonQuery[uint8](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "hop-limit"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).HopLimit
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/hop-limit"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/hop-limit"
func (n *Acl_AclSet_AclEntry_Ipv4_HopLimitPathAny) State() ygnmi.WildcardQuery[uint8] {
	return ygnmi.NewWildcardQuery[uint8](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "hop-limit"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).HopLimit
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/hop-limit"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/hop-limit"
func (n *Acl_AclSet_AclEntry_Ipv4_HopLimitPath) Config() ygnmi.ConfigQuery[uint8] {
	return ygnmi.NewConfigQuery[uint8](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "hop-limit"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).HopLimit
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/hop-limit"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/hop-limit"
func (n *Acl_AclSet_AclEntry_Ipv4_HopLimitPathAny) Config() ygnmi.WildcardQuery[uint8] {
	return ygnmi.NewWildcardQuery[uint8](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "hop-limit"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).HopLimit
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Ipv4_LengthPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/length YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_LengthPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Ipv4_LengthPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/length YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_LengthPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Ipv4_LengthPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/length"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/length"
func (n *Acl_AclSet_AclEntry_Ipv4_LengthPath) State() ygnmi.SingletonQuery[uint16] {
	return ygnmi.NewSingletonQuery[uint16](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "length"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint16, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).Length
			if ret == nil {
				var zero uint16
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/length"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/length"
func (n *Acl_AclSet_AclEntry_Ipv4_LengthPathAny) State() ygnmi.WildcardQuery[uint16] {
	return ygnmi.NewWildcardQuery[uint16](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "length"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint16, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).Length
			if ret == nil {
				var zero uint16
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/length"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/length"
func (n *Acl_AclSet_AclEntry_Ipv4_LengthPath) Config() ygnmi.ConfigQuery[uint16] {
	return ygnmi.NewConfigQuery[uint16](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "length"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint16, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).Length
			if ret == nil {
				var zero uint16
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/length"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/length"
func (n *Acl_AclSet_AclEntry_Ipv4_LengthPathAny) Config() ygnmi.WildcardQuery[uint16] {
	return ygnmi.NewWildcardQuery[uint16](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "length"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint16, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).Length
			if ret == nil {
				var zero uint16
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Ipv4_ProtocolPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/protocol YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_ProtocolPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Ipv4_ProtocolPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/protocol YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_ProtocolPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Ipv4_ProtocolPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/protocol"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/protocol"
func (n *Acl_AclSet_AclEntry_Ipv4_ProtocolPath) State() ygnmi.SingletonQuery[oc.Acl_AclSet_AclEntry_Ipv4_Protocol_Union] {
	return ygnmi.NewSingletonQuery[oc.Acl_AclSet_AclEntry_Ipv4_Protocol_Union](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "protocol"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.Acl_AclSet_AclEntry_Ipv4_Protocol_Union, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).Protocol
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/protocol"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/protocol"
func (n *Acl_AclSet_AclEntry_Ipv4_ProtocolPathAny) State() ygnmi.WildcardQuery[oc.Acl_AclSet_AclEntry_Ipv4_Protocol_Union] {
	return ygnmi.NewWildcardQuery[oc.Acl_AclSet_AclEntry_Ipv4_Protocol_Union](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "protocol"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.Acl_AclSet_AclEntry_Ipv4_Protocol_Union, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).Protocol
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/protocol"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/protocol"
func (n *Acl_AclSet_AclEntry_Ipv4_ProtocolPath) Config() ygnmi.ConfigQuery[oc.Acl_AclSet_AclEntry_Ipv4_Protocol_Union] {
	return ygnmi.NewConfigQuery[oc.Acl_AclSet_AclEntry_Ipv4_Protocol_Union](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "protocol"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.Acl_AclSet_AclEntry_Ipv4_Protocol_Union, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).Protocol
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/protocol"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/protocol"
func (n *Acl_AclSet_AclEntry_Ipv4_ProtocolPathAny) Config() ygnmi.WildcardQuery[oc.Acl_AclSet_AclEntry_Ipv4_Protocol_Union] {
	return ygnmi.NewWildcardQuery[oc.Acl_AclSet_AclEntry_Ipv4_Protocol_Union](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "protocol"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.Acl_AclSet_AclEntry_Ipv4_Protocol_Union, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).Protocol
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Ipv4_SourceAddressPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/source-address YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_SourceAddressPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Ipv4_SourceAddressPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/source-address YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_SourceAddressPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Ipv4_SourceAddressPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/source-address"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/source-address"
func (n *Acl_AclSet_AclEntry_Ipv4_SourceAddressPath) State() ygnmi.SingletonQuery[string] {
	return ygnmi.NewSingletonQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "source-address"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).SourceAddress
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/source-address"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/source-address"
func (n *Acl_AclSet_AclEntry_Ipv4_SourceAddressPathAny) State() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "source-address"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).SourceAddress
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/source-address"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/source-address"
func (n *Acl_AclSet_AclEntry_Ipv4_SourceAddressPath) Config() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "source-address"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).SourceAddress
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/source-address"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/source-address"
func (n *Acl_AclSet_AclEntry_Ipv4_SourceAddressPathAny) Config() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "source-address"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).SourceAddress
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_AclSet_AclEntry_Ipv4_SourceAddressPrefixSetPath represents the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/source-address-prefix-set YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_SourceAddressPrefixSetPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_AclSet_AclEntry_Ipv4_SourceAddressPrefixSetPathAny represents the wildcard version of the /openconfig-acl/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/source-address-prefix-set YANG schema element.
type Acl_AclSet_AclEntry_Ipv4_SourceAddressPrefixSetPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_AclSet_AclEntry_Ipv4_SourceAddressPrefixSetPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/source-address-prefix-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/source-address-prefix-set"
func (n *Acl_AclSet_AclEntry_Ipv4_SourceAddressPrefixSetPath) State() ygnmi.SingletonQuery[string] {
	return ygnmi.NewSingletonQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "source-address-prefix-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).SourceAddressPrefixSet
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/source-address-prefix-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/state/source-address-prefix-set"
func (n *Acl_AclSet_AclEntry_Ipv4_SourceAddressPrefixSetPathAny) State() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "source-address-prefix-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).SourceAddressPrefixSet
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/source-address-prefix-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/source-address-prefix-set"
func (n *Acl_AclSet_AclEntry_Ipv4_SourceAddressPrefixSetPath) Config() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "source-address-prefix-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).SourceAddressPrefixSet
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-packet-match"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/source-address-prefix-set"
// 	Path from root:       "/acl/acl-sets/acl-set/acl-entries/acl-entry/ipv4/config/source-address-prefix-set"
func (n *Acl_AclSet_AclEntry_Ipv4_SourceAddressPrefixSetPathAny) Config() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Acl_AclSet_AclEntry_Ipv4",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "source-address-prefix-set"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_AclSet_AclEntry_Ipv4).SourceAddressPrefixSet
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_AclSet_AclEntry_Ipv4) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}
