/*
Package openconfigacl is a generated package which contains definitions
of structs which generate gNMI paths for a YANG schema.

This package was generated by ygnmi version: v0.15.0: (ygot: v0.35.0)
using the following YANG input files:
	- ./yang-repo/openconfig/interfaces/openconfig-interfaces.yang
	- ./yang-repo/openconfig/interfaces/openconfig-if-ip.yang
	- ./yang-repo/openconfig/bgp/openconfig-bgp.yang
	- ./yang-repo/openconfig/acl/openconfig-acl.yang
	- ./yang-repo/openconfig/network-instance/openconfig-network-instance.yang
	- ./yang-repo/openconfig/system/openconfig-system.yang
Imported modules were sourced from:
	- ./yang-repo
	- ./yang-repo/iana
	- ./yang-repo/ietf
	- ./yang-repo/mappings
	- ./yang-repo/mappings/openconfig
	- ./yang-repo/openconfig
	- ./yang-repo/openconfig/acl
	- ./yang-repo/openconfig/aft
	- ./yang-repo/openconfig/bfd
	- ./yang-repo/openconfig/bgp
	- ./yang-repo/openconfig/defined-sets
	- ./yang-repo/openconfig/extensions
	- ./yang-repo/openconfig/flex-algo
	- ./yang-repo/openconfig/gnsi
	- ./yang-repo/openconfig/gribi
	- ./yang-repo/openconfig/interfaces
	- ./yang-repo/openconfig/isis
	- ./yang-repo/openconfig/keychain
	- ./yang-repo/openconfig/lacp
	- ./yang-repo/openconfig/lldp
	- ./yang-repo/openconfig/local-routing
	- ./yang-repo/openconfig/mpls
	- ./yang-repo/openconfig/multicast
	- ./yang-repo/openconfig/network-instance
	- ./yang-repo/openconfig/optical-transport
	- ./yang-repo/openconfig/ospf
	- ./yang-repo/openconfig/p4rt
	- ./yang-repo/openconfig/pcep
	- ./yang-repo/openconfig/platform
	- ./yang-repo/openconfig/policy-forwarding
	- ./yang-repo/openconfig/policy
	- ./yang-repo/openconfig/qos
	- ./yang-repo/openconfig/rib
	- ./yang-repo/openconfig/sampling
	- ./yang-repo/openconfig/segment-routing
	- ./yang-repo/openconfig/stp
	- ./yang-repo/openconfig/system
	- ./yang-repo/openconfig/test
	- ./yang-repo/openconfig/types
	- ./yang-repo/openconfig/vlan
	- ./yang-repo/srl_nokia
	- ./yang-repo/srl_nokia/models
	- ./yang-repo/srl_nokia/models/acl
	- ./yang-repo/srl_nokia/models/bfd
	- ./yang-repo/srl_nokia/models/common
	- ./yang-repo/srl_nokia/models/ethcfm
	- ./yang-repo/srl_nokia/models/grpc
	- ./yang-repo/srl_nokia/models/interfaces
	- ./yang-repo/srl_nokia/models/ndk
	- ./yang-repo/srl_nokia/models/network-instance
	- ./yang-repo/srl_nokia/models/oam
	- ./yang-repo/srl_nokia/models/platform
	- ./yang-repo/srl_nokia/models/qos
	- ./yang-repo/srl_nokia/models/routing-policy
	- ./yang-repo/srl_nokia/models/service-activation-testhead
	- ./yang-repo/srl_nokia/models/stp
	- ./yang-repo/srl_nokia/models/subscriber-mgmt
	- ./yang-repo/srl_nokia/models/sync
	- ./yang-repo/srl_nokia/models/system
	- ./yang-repo/srl_nokia/models/transport-security
	- ./yang-repo/srl_nokia/models/tunnel
	- ./yang-repo/srl_nokia/models/twamp
*/
package openconfigacl

import (
	"reflect"
	oc "github.com/LeBaoTai/SDN-RD/internal/oc"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygnmi/ygnmi"
	"github.com/openconfig/ygot/ytypes"
)

// Acl_Interface_EgressAclSet_AclEntryPath represents the /openconfig-acl/acl/interfaces/interface/egress-acl-sets/egress-acl-set/acl-entries/acl-entry YANG schema element.
type Acl_Interface_EgressAclSet_AclEntryPath struct {
	*ygnmi.NodePath
}

// Acl_Interface_EgressAclSet_AclEntryPathAny represents the wildcard version of the /openconfig-acl/acl/interfaces/interface/egress-acl-sets/egress-acl-set/acl-entries/acl-entry YANG schema element.
type Acl_Interface_EgressAclSet_AclEntryPathAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_Interface_EgressAclSet_AclEntryPath) PathOriginName() string {
     return "openconfig"
}

// Acl_Interface_EgressAclSet_AclEntryPathMap represents the /openconfig-acl/acl/interfaces/interface/egress-acl-sets/egress-acl-set/acl-entries/acl-entry YANG schema element.
type Acl_Interface_EgressAclSet_AclEntryPathMap struct {
	*ygnmi.NodePath
}

// Acl_Interface_EgressAclSet_AclEntryPathMapAny represents the wildcard version of the /openconfig-acl/acl/interfaces/interface/egress-acl-sets/egress-acl-set/acl-entries/acl-entry YANG schema element.
type Acl_Interface_EgressAclSet_AclEntryPathMapAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_Interface_EgressAclSet_AclEntryPathMap) PathOriginName() string {
     return "openconfig"
}

// MatchedOctets (leaf): Count of the number of octets (bytes) matching the current
// ACL entry.
// 
// An implementation should provide this counter on a
// per-interface per-ACL-entry if possible.
// 
// If an implementation only supports ACL counters per entry
// (i.e., not broken out per interface), then the value
// should be equal to the aggregate count across all interfaces.
// 
// An implementation that provides counters per entry per
// interface is not required to also provide an aggregate count,
// e.g., per entry -- the user is expected to be able implement
// the required aggregation if such a count is needed.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/matched-octets"
// 	Path from root:       "/acl/interfaces/interface/egress-acl-sets/egress-acl-set/acl-entries/acl-entry/state/matched-octets"
func (n *Acl_Interface_EgressAclSet_AclEntryPath) MatchedOctets() *Acl_Interface_EgressAclSet_AclEntry_MatchedOctetsPath {
	ps := &Acl_Interface_EgressAclSet_AclEntry_MatchedOctetsPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "matched-octets"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// MatchedOctets (leaf): Count of the number of octets (bytes) matching the current
// ACL entry.
// 
// An implementation should provide this counter on a
// per-interface per-ACL-entry if possible.
// 
// If an implementation only supports ACL counters per entry
// (i.e., not broken out per interface), then the value
// should be equal to the aggregate count across all interfaces.
// 
// An implementation that provides counters per entry per
// interface is not required to also provide an aggregate count,
// e.g., per entry -- the user is expected to be able implement
// the required aggregation if such a count is needed.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/matched-octets"
// 	Path from root:       "/acl/interfaces/interface/egress-acl-sets/egress-acl-set/acl-entries/acl-entry/state/matched-octets"
func (n *Acl_Interface_EgressAclSet_AclEntryPathAny) MatchedOctets() *Acl_Interface_EgressAclSet_AclEntry_MatchedOctetsPathAny {
	ps := &Acl_Interface_EgressAclSet_AclEntry_MatchedOctetsPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "matched-octets"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// MatchedPackets (leaf): Count of the number of packets matching the current ACL
// entry.
// 
// An implementation should provide this counter on a
// per-interface per-ACL-entry if possible.
// 
// If an implementation only supports ACL counters per entry
// (i.e., not broken out per interface), then the value
// should be equal to the aggregate count across all interfaces.
// 
// An implementation that provides counters per entry per
// interface is not required to also provide an aggregate count,
// e.g., per entry -- the user is expected to be able implement
// the required aggregation if such a count is needed.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/matched-packets"
// 	Path from root:       "/acl/interfaces/interface/egress-acl-sets/egress-acl-set/acl-entries/acl-entry/state/matched-packets"
func (n *Acl_Interface_EgressAclSet_AclEntryPath) MatchedPackets() *Acl_Interface_EgressAclSet_AclEntry_MatchedPacketsPath {
	ps := &Acl_Interface_EgressAclSet_AclEntry_MatchedPacketsPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "matched-packets"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// MatchedPackets (leaf): Count of the number of packets matching the current ACL
// entry.
// 
// An implementation should provide this counter on a
// per-interface per-ACL-entry if possible.
// 
// If an implementation only supports ACL counters per entry
// (i.e., not broken out per interface), then the value
// should be equal to the aggregate count across all interfaces.
// 
// An implementation that provides counters per entry per
// interface is not required to also provide an aggregate count,
// e.g., per entry -- the user is expected to be able implement
// the required aggregation if such a count is needed.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/matched-packets"
// 	Path from root:       "/acl/interfaces/interface/egress-acl-sets/egress-acl-set/acl-entries/acl-entry/state/matched-packets"
func (n *Acl_Interface_EgressAclSet_AclEntryPathAny) MatchedPackets() *Acl_Interface_EgressAclSet_AclEntry_MatchedPacketsPathAny {
	ps := &Acl_Interface_EgressAclSet_AclEntry_MatchedPacketsPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "matched-packets"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// SequenceId (leaf): Reference to an entry in the ACL set applied to an
// interface
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/sequence-id"
// 	Path from root:       "/acl/interfaces/interface/egress-acl-sets/egress-acl-set/acl-entries/acl-entry/*/sequence-id"
func (n *Acl_Interface_EgressAclSet_AclEntryPath) SequenceId() *Acl_Interface_EgressAclSet_AclEntry_SequenceIdPath {
	ps := &Acl_Interface_EgressAclSet_AclEntry_SequenceIdPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "sequence-id"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// SequenceId (leaf): Reference to an entry in the ACL set applied to an
// interface
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/sequence-id"
// 	Path from root:       "/acl/interfaces/interface/egress-acl-sets/egress-acl-set/acl-entries/acl-entry/*/sequence-id"
func (n *Acl_Interface_EgressAclSet_AclEntryPathAny) SequenceId() *Acl_Interface_EgressAclSet_AclEntry_SequenceIdPathAny {
	ps := &Acl_Interface_EgressAclSet_AclEntry_SequenceIdPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "sequence-id"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_EgressAclSet_AclEntryPath) State() ygnmi.SingletonQuery[*oc.Acl_Interface_EgressAclSet_AclEntry] {
	return ygnmi.NewSingletonQuery[*oc.Acl_Interface_EgressAclSet_AclEntry](
		"Acl_Interface_EgressAclSet_AclEntry",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_EgressAclSet_AclEntryPathAny) State() ygnmi.WildcardQuery[*oc.Acl_Interface_EgressAclSet_AclEntry] {
	return ygnmi.NewWildcardQuery[*oc.Acl_Interface_EgressAclSet_AclEntry](
		"Acl_Interface_EgressAclSet_AclEntry",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_EgressAclSet_AclEntryPathMap) State() ygnmi.SingletonQuery[map[uint32]*oc.Acl_Interface_EgressAclSet_AclEntry] {
	return ygnmi.NewSingletonQuery[map[uint32]*oc.Acl_Interface_EgressAclSet_AclEntry](
		"Acl_Interface_EgressAclSet",
		true,
		false,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[uint32]*oc.Acl_Interface_EgressAclSet_AclEntry, bool) { 
			ret := gs.(*oc.Acl_Interface_EgressAclSet).AclEntry
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_EgressAclSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath: []string{"openconfig-acl:acl-entries"},
			PostRelPath: []string{"openconfig-acl:acl-entry"},
		},
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_EgressAclSet_AclEntryPathMapAny) State() ygnmi.WildcardQuery[map[uint32]*oc.Acl_Interface_EgressAclSet_AclEntry] {
	return ygnmi.NewWildcardQuery[map[uint32]*oc.Acl_Interface_EgressAclSet_AclEntry](
		"Acl_Interface_EgressAclSet",
		true,
		false,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[uint32]*oc.Acl_Interface_EgressAclSet_AclEntry, bool) { 
			ret := gs.(*oc.Acl_Interface_EgressAclSet).AclEntry
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_EgressAclSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath: []string{"openconfig-acl:acl-entries"},
			PostRelPath: []string{"openconfig-acl:acl-entry"},
		},
	)
}

// Acl_Interface_IngressAclSetPath represents the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set YANG schema element.
type Acl_Interface_IngressAclSetPath struct {
	*ygnmi.NodePath
}

// Acl_Interface_IngressAclSetPathAny represents the wildcard version of the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set YANG schema element.
type Acl_Interface_IngressAclSetPathAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_Interface_IngressAclSetPath) PathOriginName() string {
     return ""
}

// Acl_Interface_IngressAclSetPathMap represents the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set YANG schema element.
type Acl_Interface_IngressAclSetPathMap struct {
	*ygnmi.NodePath
}

// Acl_Interface_IngressAclSetPathMapAny represents the wildcard version of the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set YANG schema element.
type Acl_Interface_IngressAclSetPathMapAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_Interface_IngressAclSetPathMap) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_IngressAclSetPathMap) State() ygnmi.SingletonQuery[*oc.Acl_Interface_IngressAclSet_OrderedMap] {
	return ygnmi.NewSingletonQuery[*oc.Acl_Interface_IngressAclSet_OrderedMap](
		"Acl_Interface",
		true,
		false,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (*oc.Acl_Interface_IngressAclSet_OrderedMap, bool) { 
			ret := gs.(*oc.Acl_Interface).IngressAclSet
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath: []string{"openconfig-acl:ingress-acl-sets"},
			PostRelPath: []string{"openconfig-acl:ingress-acl-set"},
		},
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_IngressAclSetPathMapAny) State() ygnmi.WildcardQuery[*oc.Acl_Interface_IngressAclSet_OrderedMap] {
	return ygnmi.NewWildcardQuery[*oc.Acl_Interface_IngressAclSet_OrderedMap](
		"Acl_Interface",
		true,
		false,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (*oc.Acl_Interface_IngressAclSet_OrderedMap, bool) { 
			ret := gs.(*oc.Acl_Interface).IngressAclSet
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath: []string{"openconfig-acl:ingress-acl-sets"},
			PostRelPath: []string{"openconfig-acl:ingress-acl-set"},
		},
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_IngressAclSetPathMap) Config() ygnmi.ConfigQuery[*oc.Acl_Interface_IngressAclSet_OrderedMap] {
	return ygnmi.NewConfigQuery[*oc.Acl_Interface_IngressAclSet_OrderedMap](
		"Acl_Interface",
		false,
		true,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (*oc.Acl_Interface_IngressAclSet_OrderedMap, bool) { 
			ret := gs.(*oc.Acl_Interface).IngressAclSet
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath: []string{"openconfig-acl:ingress-acl-sets"},
			PostRelPath: []string{"openconfig-acl:ingress-acl-set"},
		},
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_IngressAclSetPathMapAny) Config() ygnmi.WildcardQuery[*oc.Acl_Interface_IngressAclSet_OrderedMap] {
	return ygnmi.NewWildcardQuery[*oc.Acl_Interface_IngressAclSet_OrderedMap](
		"Acl_Interface",
		false,
		true,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (*oc.Acl_Interface_IngressAclSet_OrderedMap, bool) { 
			ret := gs.(*oc.Acl_Interface).IngressAclSet
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath: []string{"openconfig-acl:ingress-acl-sets"},
			PostRelPath: []string{"openconfig-acl:ingress-acl-set"},
		},
	)
}

// Acl_Interface_IngressAclSet_AclEntry_MatchedOctetsPath represents the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/matched-octets YANG schema element.
type Acl_Interface_IngressAclSet_AclEntry_MatchedOctetsPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_Interface_IngressAclSet_AclEntry_MatchedOctetsPathAny represents the wildcard version of the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/matched-octets YANG schema element.
type Acl_Interface_IngressAclSet_AclEntry_MatchedOctetsPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_Interface_IngressAclSet_AclEntry_MatchedOctetsPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/matched-octets"
// 	Path from root:       "/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/matched-octets"
func (n *Acl_Interface_IngressAclSet_AclEntry_MatchedOctetsPath) State() ygnmi.SingletonQuery[uint64] {
	return ygnmi.NewSingletonQuery[uint64](
		"Acl_Interface_IngressAclSet_AclEntry",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "matched-octets"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Acl_Interface_IngressAclSet_AclEntry).MatchedOctets
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_IngressAclSet_AclEntry) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/matched-octets"
// 	Path from root:       "/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/matched-octets"
func (n *Acl_Interface_IngressAclSet_AclEntry_MatchedOctetsPathAny) State() ygnmi.WildcardQuery[uint64] {
	return ygnmi.NewWildcardQuery[uint64](
		"Acl_Interface_IngressAclSet_AclEntry",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "matched-octets"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Acl_Interface_IngressAclSet_AclEntry).MatchedOctets
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_IngressAclSet_AclEntry) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_Interface_IngressAclSet_AclEntry_MatchedPacketsPath represents the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/matched-packets YANG schema element.
type Acl_Interface_IngressAclSet_AclEntry_MatchedPacketsPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_Interface_IngressAclSet_AclEntry_MatchedPacketsPathAny represents the wildcard version of the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/matched-packets YANG schema element.
type Acl_Interface_IngressAclSet_AclEntry_MatchedPacketsPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_Interface_IngressAclSet_AclEntry_MatchedPacketsPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/matched-packets"
// 	Path from root:       "/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/matched-packets"
func (n *Acl_Interface_IngressAclSet_AclEntry_MatchedPacketsPath) State() ygnmi.SingletonQuery[uint64] {
	return ygnmi.NewSingletonQuery[uint64](
		"Acl_Interface_IngressAclSet_AclEntry",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "matched-packets"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Acl_Interface_IngressAclSet_AclEntry).MatchedPackets
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_IngressAclSet_AclEntry) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/matched-packets"
// 	Path from root:       "/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/matched-packets"
func (n *Acl_Interface_IngressAclSet_AclEntry_MatchedPacketsPathAny) State() ygnmi.WildcardQuery[uint64] {
	return ygnmi.NewWildcardQuery[uint64](
		"Acl_Interface_IngressAclSet_AclEntry",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "matched-packets"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Acl_Interface_IngressAclSet_AclEntry).MatchedPackets
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_IngressAclSet_AclEntry) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_Interface_IngressAclSet_AclEntry_SequenceIdPath represents the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/sequence-id YANG schema element.
type Acl_Interface_IngressAclSet_AclEntry_SequenceIdPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_Interface_IngressAclSet_AclEntry_SequenceIdPathAny represents the wildcard version of the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/sequence-id YANG schema element.
type Acl_Interface_IngressAclSet_AclEntry_SequenceIdPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_Interface_IngressAclSet_AclEntry_SequenceIdPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/sequence-id"
// 	Path from root:       "/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/sequence-id"
func (n *Acl_Interface_IngressAclSet_AclEntry_SequenceIdPath) State() ygnmi.SingletonQuery[uint32] {
	return ygnmi.NewSingletonQuery[uint32](
		"Acl_Interface_IngressAclSet_AclEntry",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "sequence-id"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) { 
			ret := gs.(*oc.Acl_Interface_IngressAclSet_AclEntry).SequenceId
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_IngressAclSet_AclEntry) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/sequence-id"
// 	Path from root:       "/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/sequence-id"
func (n *Acl_Interface_IngressAclSet_AclEntry_SequenceIdPathAny) State() ygnmi.WildcardQuery[uint32] {
	return ygnmi.NewWildcardQuery[uint32](
		"Acl_Interface_IngressAclSet_AclEntry",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "sequence-id"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) { 
			ret := gs.(*oc.Acl_Interface_IngressAclSet_AclEntry).SequenceId
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_IngressAclSet_AclEntry) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "sequence-id"
// 	Path from root:       ""
func (n *Acl_Interface_IngressAclSet_AclEntry_SequenceIdPath) Config() ygnmi.ConfigQuery[uint32] {
	return ygnmi.NewConfigQuery[uint32](
		"Acl_Interface_IngressAclSet_AclEntry",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"sequence-id"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) { 
			ret := gs.(*oc.Acl_Interface_IngressAclSet_AclEntry).SequenceId
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_IngressAclSet_AclEntry) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "sequence-id"
// 	Path from root:       ""
func (n *Acl_Interface_IngressAclSet_AclEntry_SequenceIdPathAny) Config() ygnmi.WildcardQuery[uint32] {
	return ygnmi.NewWildcardQuery[uint32](
		"Acl_Interface_IngressAclSet_AclEntry",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"sequence-id"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) { 
			ret := gs.(*oc.Acl_Interface_IngressAclSet_AclEntry).SequenceId
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_IngressAclSet_AclEntry) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_Interface_IngressAclSet_AclEntryPath represents the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry YANG schema element.
type Acl_Interface_IngressAclSet_AclEntryPath struct {
	*ygnmi.NodePath
}

// Acl_Interface_IngressAclSet_AclEntryPathAny represents the wildcard version of the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry YANG schema element.
type Acl_Interface_IngressAclSet_AclEntryPathAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_Interface_IngressAclSet_AclEntryPath) PathOriginName() string {
     return "openconfig"
}

// Acl_Interface_IngressAclSet_AclEntryPathMap represents the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry YANG schema element.
type Acl_Interface_IngressAclSet_AclEntryPathMap struct {
	*ygnmi.NodePath
}

// Acl_Interface_IngressAclSet_AclEntryPathMapAny represents the wildcard version of the /openconfig-acl/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry YANG schema element.
type Acl_Interface_IngressAclSet_AclEntryPathMapAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_Interface_IngressAclSet_AclEntryPathMap) PathOriginName() string {
     return "openconfig"
}

// MatchedOctets (leaf): Count of the number of octets (bytes) matching the current
// ACL entry.
// 
// An implementation should provide this counter on a
// per-interface per-ACL-entry if possible.
// 
// If an implementation only supports ACL counters per entry
// (i.e., not broken out per interface), then the value
// should be equal to the aggregate count across all interfaces.
// 
// An implementation that provides counters per entry per
// interface is not required to also provide an aggregate count,
// e.g., per entry -- the user is expected to be able implement
// the required aggregation if such a count is needed.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/matched-octets"
// 	Path from root:       "/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/matched-octets"
func (n *Acl_Interface_IngressAclSet_AclEntryPath) MatchedOctets() *Acl_Interface_IngressAclSet_AclEntry_MatchedOctetsPath {
	ps := &Acl_Interface_IngressAclSet_AclEntry_MatchedOctetsPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "matched-octets"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// MatchedOctets (leaf): Count of the number of octets (bytes) matching the current
// ACL entry.
// 
// An implementation should provide this counter on a
// per-interface per-ACL-entry if possible.
// 
// If an implementation only supports ACL counters per entry
// (i.e., not broken out per interface), then the value
// should be equal to the aggregate count across all interfaces.
// 
// An implementation that provides counters per entry per
// interface is not required to also provide an aggregate count,
// e.g., per entry -- the user is expected to be able implement
// the required aggregation if such a count is needed.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/matched-octets"
// 	Path from root:       "/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/matched-octets"
func (n *Acl_Interface_IngressAclSet_AclEntryPathAny) MatchedOctets() *Acl_Interface_IngressAclSet_AclEntry_MatchedOctetsPathAny {
	ps := &Acl_Interface_IngressAclSet_AclEntry_MatchedOctetsPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "matched-octets"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// MatchedPackets (leaf): Count of the number of packets matching the current ACL
// entry.
// 
// An implementation should provide this counter on a
// per-interface per-ACL-entry if possible.
// 
// If an implementation only supports ACL counters per entry
// (i.e., not broken out per interface), then the value
// should be equal to the aggregate count across all interfaces.
// 
// An implementation that provides counters per entry per
// interface is not required to also provide an aggregate count,
// e.g., per entry -- the user is expected to be able implement
// the required aggregation if such a count is needed.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/matched-packets"
// 	Path from root:       "/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/matched-packets"
func (n *Acl_Interface_IngressAclSet_AclEntryPath) MatchedPackets() *Acl_Interface_IngressAclSet_AclEntry_MatchedPacketsPath {
	ps := &Acl_Interface_IngressAclSet_AclEntry_MatchedPacketsPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "matched-packets"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// MatchedPackets (leaf): Count of the number of packets matching the current ACL
// entry.
// 
// An implementation should provide this counter on a
// per-interface per-ACL-entry if possible.
// 
// If an implementation only supports ACL counters per entry
// (i.e., not broken out per interface), then the value
// should be equal to the aggregate count across all interfaces.
// 
// An implementation that provides counters per entry per
// interface is not required to also provide an aggregate count,
// e.g., per entry -- the user is expected to be able implement
// the required aggregation if such a count is needed.
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/matched-packets"
// 	Path from root:       "/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/state/matched-packets"
func (n *Acl_Interface_IngressAclSet_AclEntryPathAny) MatchedPackets() *Acl_Interface_IngressAclSet_AclEntry_MatchedPacketsPathAny {
	ps := &Acl_Interface_IngressAclSet_AclEntry_MatchedPacketsPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "matched-packets"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// SequenceId (leaf): Reference to an entry in the ACL set applied to an
// interface
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/sequence-id"
// 	Path from root:       "/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/*/sequence-id"
func (n *Acl_Interface_IngressAclSet_AclEntryPath) SequenceId() *Acl_Interface_IngressAclSet_AclEntry_SequenceIdPath {
	ps := &Acl_Interface_IngressAclSet_AclEntry_SequenceIdPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "sequence-id"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// SequenceId (leaf): Reference to an entry in the ACL set applied to an
// interface
// 	Defining module:      "openconfig-acl"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/sequence-id"
// 	Path from root:       "/acl/interfaces/interface/ingress-acl-sets/ingress-acl-set/acl-entries/acl-entry/*/sequence-id"
func (n *Acl_Interface_IngressAclSet_AclEntryPathAny) SequenceId() *Acl_Interface_IngressAclSet_AclEntry_SequenceIdPathAny {
	ps := &Acl_Interface_IngressAclSet_AclEntry_SequenceIdPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "sequence-id"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_IngressAclSet_AclEntryPath) State() ygnmi.SingletonQuery[*oc.Acl_Interface_IngressAclSet_AclEntry] {
	return ygnmi.NewSingletonQuery[*oc.Acl_Interface_IngressAclSet_AclEntry](
		"Acl_Interface_IngressAclSet_AclEntry",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_IngressAclSet_AclEntryPathAny) State() ygnmi.WildcardQuery[*oc.Acl_Interface_IngressAclSet_AclEntry] {
	return ygnmi.NewWildcardQuery[*oc.Acl_Interface_IngressAclSet_AclEntry](
		"Acl_Interface_IngressAclSet_AclEntry",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_IngressAclSet_AclEntryPathMap) State() ygnmi.SingletonQuery[map[uint32]*oc.Acl_Interface_IngressAclSet_AclEntry] {
	return ygnmi.NewSingletonQuery[map[uint32]*oc.Acl_Interface_IngressAclSet_AclEntry](
		"Acl_Interface_IngressAclSet",
		true,
		false,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[uint32]*oc.Acl_Interface_IngressAclSet_AclEntry, bool) { 
			ret := gs.(*oc.Acl_Interface_IngressAclSet).AclEntry
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_IngressAclSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath: []string{"openconfig-acl:acl-entries"},
			PostRelPath: []string{"openconfig-acl:acl-entry"},
		},
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_IngressAclSet_AclEntryPathMapAny) State() ygnmi.WildcardQuery[map[uint32]*oc.Acl_Interface_IngressAclSet_AclEntry] {
	return ygnmi.NewWildcardQuery[map[uint32]*oc.Acl_Interface_IngressAclSet_AclEntry](
		"Acl_Interface_IngressAclSet",
		true,
		false,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[uint32]*oc.Acl_Interface_IngressAclSet_AclEntry, bool) { 
			ret := gs.(*oc.Acl_Interface_IngressAclSet).AclEntry
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_IngressAclSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath: []string{"openconfig-acl:acl-entries"},
			PostRelPath: []string{"openconfig-acl:acl-entry"},
		},
	)
}

// Acl_Interface_InterfaceRef_InterfacePath represents the /openconfig-acl/acl/interfaces/interface/interface-ref/state/interface YANG schema element.
type Acl_Interface_InterfaceRef_InterfacePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_Interface_InterfaceRef_InterfacePathAny represents the wildcard version of the /openconfig-acl/acl/interfaces/interface/interface-ref/state/interface YANG schema element.
type Acl_Interface_InterfaceRef_InterfacePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_Interface_InterfaceRef_InterfacePath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-interfaces"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/interface"
// 	Path from root:       "/acl/interfaces/interface/interface-ref/state/interface"
func (n *Acl_Interface_InterfaceRef_InterfacePath) State() ygnmi.SingletonQuery[string] {
	return ygnmi.NewSingletonQuery[string](
		"Acl_Interface_InterfaceRef",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "interface"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_Interface_InterfaceRef).Interface
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_InterfaceRef) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-interfaces"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/interface"
// 	Path from root:       "/acl/interfaces/interface/interface-ref/state/interface"
func (n *Acl_Interface_InterfaceRef_InterfacePathAny) State() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Acl_Interface_InterfaceRef",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "interface"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_Interface_InterfaceRef).Interface
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_InterfaceRef) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-interfaces"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/interface"
// 	Path from root:       "/acl/interfaces/interface/interface-ref/config/interface"
func (n *Acl_Interface_InterfaceRef_InterfacePath) Config() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"Acl_Interface_InterfaceRef",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "interface"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_Interface_InterfaceRef).Interface
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_InterfaceRef) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-interfaces"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/interface"
// 	Path from root:       "/acl/interfaces/interface/interface-ref/config/interface"
func (n *Acl_Interface_InterfaceRef_InterfacePathAny) Config() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Acl_Interface_InterfaceRef",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "interface"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Acl_Interface_InterfaceRef).Interface
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_InterfaceRef) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_Interface_InterfaceRef_SubinterfacePath represents the /openconfig-acl/acl/interfaces/interface/interface-ref/state/subinterface YANG schema element.
type Acl_Interface_InterfaceRef_SubinterfacePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Acl_Interface_InterfaceRef_SubinterfacePathAny represents the wildcard version of the /openconfig-acl/acl/interfaces/interface/interface-ref/state/subinterface YANG schema element.
type Acl_Interface_InterfaceRef_SubinterfacePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_Interface_InterfaceRef_SubinterfacePath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-interfaces"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/subinterface"
// 	Path from root:       "/acl/interfaces/interface/interface-ref/state/subinterface"
func (n *Acl_Interface_InterfaceRef_SubinterfacePath) State() ygnmi.SingletonQuery[uint32] {
	return ygnmi.NewSingletonQuery[uint32](
		"Acl_Interface_InterfaceRef",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "subinterface"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) { 
			ret := gs.(*oc.Acl_Interface_InterfaceRef).Subinterface
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_InterfaceRef) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-interfaces"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "state/subinterface"
// 	Path from root:       "/acl/interfaces/interface/interface-ref/state/subinterface"
func (n *Acl_Interface_InterfaceRef_SubinterfacePathAny) State() ygnmi.WildcardQuery[uint32] {
	return ygnmi.NewWildcardQuery[uint32](
		"Acl_Interface_InterfaceRef",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "subinterface"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) { 
			ret := gs.(*oc.Acl_Interface_InterfaceRef).Subinterface
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_InterfaceRef) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-interfaces"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/subinterface"
// 	Path from root:       "/acl/interfaces/interface/interface-ref/config/subinterface"
func (n *Acl_Interface_InterfaceRef_SubinterfacePath) Config() ygnmi.ConfigQuery[uint32] {
	return ygnmi.NewConfigQuery[uint32](
		"Acl_Interface_InterfaceRef",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "subinterface"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) { 
			ret := gs.(*oc.Acl_Interface_InterfaceRef).Subinterface
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_InterfaceRef) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-interfaces"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "config/subinterface"
// 	Path from root:       "/acl/interfaces/interface/interface-ref/config/subinterface"
func (n *Acl_Interface_InterfaceRef_SubinterfacePathAny) Config() ygnmi.WildcardQuery[uint32] {
	return ygnmi.NewWildcardQuery[uint32](
		"Acl_Interface_InterfaceRef",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "subinterface"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) { 
			ret := gs.(*oc.Acl_Interface_InterfaceRef).Subinterface
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Acl_Interface_InterfaceRef) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Acl_Interface_InterfaceRefPath represents the /openconfig-acl/acl/interfaces/interface/interface-ref YANG schema element.
type Acl_Interface_InterfaceRefPath struct {
	*ygnmi.NodePath
}

// Acl_Interface_InterfaceRefPathAny represents the wildcard version of the /openconfig-acl/acl/interfaces/interface/interface-ref YANG schema element.
type Acl_Interface_InterfaceRefPathAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *Acl_Interface_InterfaceRefPath) PathOriginName() string {
     return "openconfig"
}

// Interface (leaf): Reference to a base interface.  If a reference to a
// subinterface is required, this leaf must be specified
// to indicate the base interface.
// 	Defining module:      "openconfig-interfaces"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/interface"
// 	Path from root:       "/acl/interfaces/interface/interface-ref/*/interface"
func (n *Acl_Interface_InterfaceRefPath) Interface() *Acl_Interface_InterfaceRef_InterfacePath {
	ps := &Acl_Interface_InterfaceRef_InterfacePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "interface"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// Interface (leaf): Reference to a base interface.  If a reference to a
// subinterface is required, this leaf must be specified
// to indicate the base interface.
// 	Defining module:      "openconfig-interfaces"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/interface"
// 	Path from root:       "/acl/interfaces/interface/interface-ref/*/interface"
func (n *Acl_Interface_InterfaceRefPathAny) Interface() *Acl_Interface_InterfaceRef_InterfacePathAny {
	ps := &Acl_Interface_InterfaceRef_InterfacePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "interface"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// Subinterface (leaf): Reference to a subinterface -- this requires the base
// interface to be specified using the interface leaf in
// this container.  If only a reference to a base interface
// is required, this leaf should not be set.
// 	Defining module:      "openconfig-interfaces"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/subinterface"
// 	Path from root:       "/acl/interfaces/interface/interface-ref/*/subinterface"
func (n *Acl_Interface_InterfaceRefPath) Subinterface() *Acl_Interface_InterfaceRef_SubinterfacePath {
	ps := &Acl_Interface_InterfaceRef_SubinterfacePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "subinterface"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// Subinterface (leaf): Reference to a subinterface -- this requires the base
// interface to be specified using the interface leaf in
// this container.  If only a reference to a base interface
// is required, this leaf should not be set.
// 	Defining module:      "openconfig-interfaces"
// 	Instantiating module: "openconfig-acl"
// 	Path from parent:     "*/subinterface"
// 	Path from root:       "/acl/interfaces/interface/interface-ref/*/subinterface"
func (n *Acl_Interface_InterfaceRefPathAny) Subinterface() *Acl_Interface_InterfaceRef_SubinterfacePathAny {
	ps := &Acl_Interface_InterfaceRef_SubinterfacePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "subinterface"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_InterfaceRefPath) State() ygnmi.SingletonQuery[*oc.Acl_Interface_InterfaceRef] {
	return ygnmi.NewSingletonQuery[*oc.Acl_Interface_InterfaceRef](
		"Acl_Interface_InterfaceRef",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_InterfaceRefPathAny) State() ygnmi.WildcardQuery[*oc.Acl_Interface_InterfaceRef] {
	return ygnmi.NewWildcardQuery[*oc.Acl_Interface_InterfaceRef](
		"Acl_Interface_InterfaceRef",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_InterfaceRefPath) Config() ygnmi.ConfigQuery[*oc.Acl_Interface_InterfaceRef] {
	return ygnmi.NewConfigQuery[*oc.Acl_Interface_InterfaceRef](
		"Acl_Interface_InterfaceRef",
		false,
		true,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *Acl_Interface_InterfaceRefPathAny) Config() ygnmi.WildcardQuery[*oc.Acl_Interface_InterfaceRef] {
	return ygnmi.NewWildcardQuery[*oc.Acl_Interface_InterfaceRef](
		"Acl_Interface_InterfaceRef",
		false,
		true,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}
