/*
Package openconfigroutingpolicy is a generated package which contains definitions
of structs which generate gNMI paths for a YANG schema.

This package was generated by ygnmi version: v0.15.0: (ygot: v0.35.0)
using the following YANG input files:
  - ./yang-repo/openconfig/interfaces/openconfig-interfaces.yang
  - ./yang-repo/openconfig/interfaces/openconfig-if-ip.yang
  - ./yang-repo/openconfig/bgp/openconfig-bgp.yang
  - ./yang-repo/openconfig/acl/openconfig-acl.yang
  - ./yang-repo/openconfig/network-instance/openconfig-network-instance.yang
  - ./yang-repo/openconfig/system/openconfig-system.yang

Imported modules were sourced from:
  - ./yang-repo
  - ./yang-repo/iana
  - ./yang-repo/ietf
  - ./yang-repo/mappings
  - ./yang-repo/mappings/openconfig
  - ./yang-repo/openconfig
  - ./yang-repo/openconfig/acl
  - ./yang-repo/openconfig/aft
  - ./yang-repo/openconfig/bfd
  - ./yang-repo/openconfig/bgp
  - ./yang-repo/openconfig/defined-sets
  - ./yang-repo/openconfig/extensions
  - ./yang-repo/openconfig/flex-algo
  - ./yang-repo/openconfig/gnsi
  - ./yang-repo/openconfig/gribi
  - ./yang-repo/openconfig/interfaces
  - ./yang-repo/openconfig/isis
  - ./yang-repo/openconfig/keychain
  - ./yang-repo/openconfig/lacp
  - ./yang-repo/openconfig/lldp
  - ./yang-repo/openconfig/local-routing
  - ./yang-repo/openconfig/mpls
  - ./yang-repo/openconfig/multicast
  - ./yang-repo/openconfig/network-instance
  - ./yang-repo/openconfig/optical-transport
  - ./yang-repo/openconfig/ospf
  - ./yang-repo/openconfig/p4rt
  - ./yang-repo/openconfig/pcep
  - ./yang-repo/openconfig/platform
  - ./yang-repo/openconfig/policy-forwarding
  - ./yang-repo/openconfig/policy
  - ./yang-repo/openconfig/qos
  - ./yang-repo/openconfig/rib
  - ./yang-repo/openconfig/sampling
  - ./yang-repo/openconfig/segment-routing
  - ./yang-repo/openconfig/stp
  - ./yang-repo/openconfig/system
  - ./yang-repo/openconfig/test
  - ./yang-repo/openconfig/types
  - ./yang-repo/openconfig/vlan
  - ./yang-repo/srl_nokia
  - ./yang-repo/srl_nokia/models
  - ./yang-repo/srl_nokia/models/acl
  - ./yang-repo/srl_nokia/models/bfd
  - ./yang-repo/srl_nokia/models/common
  - ./yang-repo/srl_nokia/models/ethcfm
  - ./yang-repo/srl_nokia/models/grpc
  - ./yang-repo/srl_nokia/models/interfaces
  - ./yang-repo/srl_nokia/models/ndk
  - ./yang-repo/srl_nokia/models/network-instance
  - ./yang-repo/srl_nokia/models/oam
  - ./yang-repo/srl_nokia/models/platform
  - ./yang-repo/srl_nokia/models/qos
  - ./yang-repo/srl_nokia/models/routing-policy
  - ./yang-repo/srl_nokia/models/service-activation-testhead
  - ./yang-repo/srl_nokia/models/stp
  - ./yang-repo/srl_nokia/models/subscriber-mgmt
  - ./yang-repo/srl_nokia/models/sync
  - ./yang-repo/srl_nokia/models/system
  - ./yang-repo/srl_nokia/models/transport-security
  - ./yang-repo/srl_nokia/models/tunnel
  - ./yang-repo/srl_nokia/models/twamp
*/
package openconfigroutingpolicy

import (
	"reflect"

	oc "github.com/LeBaoTai/SDN-RD/internal/oc"
	"github.com/openconfig/ygnmi/ygnmi"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygot/ytypes"
)

// RoutingPolicy_DefinedSets_TagSet_TagValuePath represents the /openconfig-routing-policy/routing-policy/defined-sets/tag-sets/tag-set/state/tag-value YANG schema element.
type RoutingPolicy_DefinedSets_TagSet_TagValuePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// RoutingPolicy_DefinedSets_TagSet_TagValuePathAny represents the wildcard version of the /openconfig-routing-policy/routing-policy/defined-sets/tag-sets/tag-set/state/tag-value YANG schema element.
type RoutingPolicy_DefinedSets_TagSet_TagValuePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *RoutingPolicy_DefinedSets_TagSet_TagValuePath) PathOriginName() string {
	return ""
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "state/tag-value"
//	Path from root:       "/routing-policy/defined-sets/tag-sets/tag-set/state/tag-value"
func (n *RoutingPolicy_DefinedSets_TagSet_TagValuePath) State() ygnmi.SingletonQuery[[]oc.RoutingPolicy_DefinedSets_TagSet_TagValue_Union] {
	return ygnmi.NewSingletonQuery[[]oc.RoutingPolicy_DefinedSets_TagSet_TagValue_Union](
		"RoutingPolicy_DefinedSets_TagSet",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "tag-value"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.RoutingPolicy_DefinedSets_TagSet_TagValue_Union, bool) {
			ret := gs.(*oc.RoutingPolicy_DefinedSets_TagSet).TagValue
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy_DefinedSets_TagSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "state/tag-value"
//	Path from root:       "/routing-policy/defined-sets/tag-sets/tag-set/state/tag-value"
func (n *RoutingPolicy_DefinedSets_TagSet_TagValuePathAny) State() ygnmi.WildcardQuery[[]oc.RoutingPolicy_DefinedSets_TagSet_TagValue_Union] {
	return ygnmi.NewWildcardQuery[[]oc.RoutingPolicy_DefinedSets_TagSet_TagValue_Union](
		"RoutingPolicy_DefinedSets_TagSet",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "tag-value"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.RoutingPolicy_DefinedSets_TagSet_TagValue_Union, bool) {
			ret := gs.(*oc.RoutingPolicy_DefinedSets_TagSet).TagValue
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy_DefinedSets_TagSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "config/tag-value"
//	Path from root:       "/routing-policy/defined-sets/tag-sets/tag-set/config/tag-value"
func (n *RoutingPolicy_DefinedSets_TagSet_TagValuePath) Config() ygnmi.ConfigQuery[[]oc.RoutingPolicy_DefinedSets_TagSet_TagValue_Union] {
	return ygnmi.NewConfigQuery[[]oc.RoutingPolicy_DefinedSets_TagSet_TagValue_Union](
		"RoutingPolicy_DefinedSets_TagSet",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "tag-value"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.RoutingPolicy_DefinedSets_TagSet_TagValue_Union, bool) {
			ret := gs.(*oc.RoutingPolicy_DefinedSets_TagSet).TagValue
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy_DefinedSets_TagSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "config/tag-value"
//	Path from root:       "/routing-policy/defined-sets/tag-sets/tag-set/config/tag-value"
func (n *RoutingPolicy_DefinedSets_TagSet_TagValuePathAny) Config() ygnmi.WildcardQuery[[]oc.RoutingPolicy_DefinedSets_TagSet_TagValue_Union] {
	return ygnmi.NewWildcardQuery[[]oc.RoutingPolicy_DefinedSets_TagSet_TagValue_Union](
		"RoutingPolicy_DefinedSets_TagSet",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "tag-value"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.RoutingPolicy_DefinedSets_TagSet_TagValue_Union, bool) {
			ret := gs.(*oc.RoutingPolicy_DefinedSets_TagSet).TagValue
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy_DefinedSets_TagSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// RoutingPolicy_DefinedSets_TagSetPath represents the /openconfig-routing-policy/routing-policy/defined-sets/tag-sets/tag-set YANG schema element.
type RoutingPolicy_DefinedSets_TagSetPath struct {
	*ygnmi.NodePath
}

// RoutingPolicy_DefinedSets_TagSetPathAny represents the wildcard version of the /openconfig-routing-policy/routing-policy/defined-sets/tag-sets/tag-set YANG schema element.
type RoutingPolicy_DefinedSets_TagSetPathAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *RoutingPolicy_DefinedSets_TagSetPath) PathOriginName() string {
	return "openconfig"
}

// RoutingPolicy_DefinedSets_TagSetPathMap represents the /openconfig-routing-policy/routing-policy/defined-sets/tag-sets/tag-set YANG schema element.
type RoutingPolicy_DefinedSets_TagSetPathMap struct {
	*ygnmi.NodePath
}

// RoutingPolicy_DefinedSets_TagSetPathMapAny represents the wildcard version of the /openconfig-routing-policy/routing-policy/defined-sets/tag-sets/tag-set YANG schema element.
type RoutingPolicy_DefinedSets_TagSetPathMapAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *RoutingPolicy_DefinedSets_TagSetPathMap) PathOriginName() string {
	return "openconfig"
}

// Name (leaf): name / label of the tag set -- this is used to reference
// the set in match conditions
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "*/name"
//	Path from root:       "/routing-policy/defined-sets/tag-sets/tag-set/*/name"
func (n *RoutingPolicy_DefinedSets_TagSetPath) Name() *RoutingPolicy_DefinedSets_TagSet_NamePath {
	ps := &RoutingPolicy_DefinedSets_TagSet_NamePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "name"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// Name (leaf): name / label of the tag set -- this is used to reference
// the set in match conditions
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "*/name"
//	Path from root:       "/routing-policy/defined-sets/tag-sets/tag-set/*/name"
func (n *RoutingPolicy_DefinedSets_TagSetPathAny) Name() *RoutingPolicy_DefinedSets_TagSet_NamePathAny {
	ps := &RoutingPolicy_DefinedSets_TagSet_NamePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "name"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// TagValue (leaf-list): Value of the tag set member
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "*/tag-value"
//	Path from root:       "/routing-policy/defined-sets/tag-sets/tag-set/*/tag-value"
func (n *RoutingPolicy_DefinedSets_TagSetPath) TagValue() *RoutingPolicy_DefinedSets_TagSet_TagValuePath {
	ps := &RoutingPolicy_DefinedSets_TagSet_TagValuePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "tag-value"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// TagValue (leaf-list): Value of the tag set member
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "*/tag-value"
//	Path from root:       "/routing-policy/defined-sets/tag-sets/tag-set/*/tag-value"
func (n *RoutingPolicy_DefinedSets_TagSetPathAny) TagValue() *RoutingPolicy_DefinedSets_TagSet_TagValuePathAny {
	ps := &RoutingPolicy_DefinedSets_TagSet_TagValuePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "tag-value"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// State returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_DefinedSets_TagSetPath) State() ygnmi.SingletonQuery[*oc.RoutingPolicy_DefinedSets_TagSet] {
	return ygnmi.NewSingletonQuery[*oc.RoutingPolicy_DefinedSets_TagSet](
		"RoutingPolicy_DefinedSets_TagSet",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_DefinedSets_TagSetPathAny) State() ygnmi.WildcardQuery[*oc.RoutingPolicy_DefinedSets_TagSet] {
	return ygnmi.NewWildcardQuery[*oc.RoutingPolicy_DefinedSets_TagSet](
		"RoutingPolicy_DefinedSets_TagSet",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_DefinedSets_TagSetPath) Config() ygnmi.ConfigQuery[*oc.RoutingPolicy_DefinedSets_TagSet] {
	return ygnmi.NewConfigQuery[*oc.RoutingPolicy_DefinedSets_TagSet](
		"RoutingPolicy_DefinedSets_TagSet",
		false,
		true,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_DefinedSets_TagSetPathAny) Config() ygnmi.WildcardQuery[*oc.RoutingPolicy_DefinedSets_TagSet] {
	return ygnmi.NewWildcardQuery[*oc.RoutingPolicy_DefinedSets_TagSet](
		"RoutingPolicy_DefinedSets_TagSet",
		false,
		true,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_DefinedSets_TagSetPathMap) State() ygnmi.SingletonQuery[map[string]*oc.RoutingPolicy_DefinedSets_TagSet] {
	return ygnmi.NewSingletonQuery[map[string]*oc.RoutingPolicy_DefinedSets_TagSet](
		"RoutingPolicy_DefinedSets",
		true,
		false,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[string]*oc.RoutingPolicy_DefinedSets_TagSet, bool) {
			ret := gs.(*oc.RoutingPolicy_DefinedSets).TagSet
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy_DefinedSets) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath:  []string{"openconfig-routing-policy:tag-sets"},
			PostRelPath: []string{"openconfig-routing-policy:tag-set"},
		},
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_DefinedSets_TagSetPathMapAny) State() ygnmi.WildcardQuery[map[string]*oc.RoutingPolicy_DefinedSets_TagSet] {
	return ygnmi.NewWildcardQuery[map[string]*oc.RoutingPolicy_DefinedSets_TagSet](
		"RoutingPolicy_DefinedSets",
		true,
		false,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[string]*oc.RoutingPolicy_DefinedSets_TagSet, bool) {
			ret := gs.(*oc.RoutingPolicy_DefinedSets).TagSet
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy_DefinedSets) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath:  []string{"openconfig-routing-policy:tag-sets"},
			PostRelPath: []string{"openconfig-routing-policy:tag-set"},
		},
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_DefinedSets_TagSetPathMap) Config() ygnmi.ConfigQuery[map[string]*oc.RoutingPolicy_DefinedSets_TagSet] {
	return ygnmi.NewConfigQuery[map[string]*oc.RoutingPolicy_DefinedSets_TagSet](
		"RoutingPolicy_DefinedSets",
		false,
		true,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[string]*oc.RoutingPolicy_DefinedSets_TagSet, bool) {
			ret := gs.(*oc.RoutingPolicy_DefinedSets).TagSet
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy_DefinedSets) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath:  []string{"openconfig-routing-policy:tag-sets"},
			PostRelPath: []string{"openconfig-routing-policy:tag-set"},
		},
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_DefinedSets_TagSetPathMapAny) Config() ygnmi.WildcardQuery[map[string]*oc.RoutingPolicy_DefinedSets_TagSet] {
	return ygnmi.NewWildcardQuery[map[string]*oc.RoutingPolicy_DefinedSets_TagSet](
		"RoutingPolicy_DefinedSets",
		false,
		true,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[string]*oc.RoutingPolicy_DefinedSets_TagSet, bool) {
			ret := gs.(*oc.RoutingPolicy_DefinedSets).TagSet
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy_DefinedSets) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath:  []string{"openconfig-routing-policy:tag-sets"},
			PostRelPath: []string{"openconfig-routing-policy:tag-set"},
		},
	)
}

// RoutingPolicy_PolicyDefinition_NamePath represents the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition/state/name YANG schema element.
type RoutingPolicy_PolicyDefinition_NamePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// RoutingPolicy_PolicyDefinition_NamePathAny represents the wildcard version of the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition/state/name YANG schema element.
type RoutingPolicy_PolicyDefinition_NamePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *RoutingPolicy_PolicyDefinition_NamePath) PathOriginName() string {
	return ""
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "state/name"
//	Path from root:       "/routing-policy/policy-definitions/policy-definition/state/name"
func (n *RoutingPolicy_PolicyDefinition_NamePath) State() ygnmi.SingletonQuery[string] {
	return ygnmi.NewSingletonQuery[string](
		"RoutingPolicy_PolicyDefinition",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "name"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.RoutingPolicy_PolicyDefinition).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy_PolicyDefinition) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "state/name"
//	Path from root:       "/routing-policy/policy-definitions/policy-definition/state/name"
func (n *RoutingPolicy_PolicyDefinition_NamePathAny) State() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"RoutingPolicy_PolicyDefinition",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "name"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.RoutingPolicy_PolicyDefinition).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy_PolicyDefinition) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "config/name"
//	Path from root:       "/routing-policy/policy-definitions/policy-definition/config/name"
func (n *RoutingPolicy_PolicyDefinition_NamePath) Config() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"RoutingPolicy_PolicyDefinition",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "name"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.RoutingPolicy_PolicyDefinition).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy_PolicyDefinition) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "config/name"
//	Path from root:       "/routing-policy/policy-definitions/policy-definition/config/name"
func (n *RoutingPolicy_PolicyDefinition_NamePathAny) Config() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"RoutingPolicy_PolicyDefinition",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "name"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.RoutingPolicy_PolicyDefinition).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy_PolicyDefinition) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// RoutingPolicy_PolicyDefinitionPath represents the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition YANG schema element.
type RoutingPolicy_PolicyDefinitionPath struct {
	*ygnmi.NodePath
}

// RoutingPolicy_PolicyDefinitionPathAny represents the wildcard version of the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition YANG schema element.
type RoutingPolicy_PolicyDefinitionPathAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *RoutingPolicy_PolicyDefinitionPath) PathOriginName() string {
	return "openconfig"
}

// RoutingPolicy_PolicyDefinitionPathMap represents the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition YANG schema element.
type RoutingPolicy_PolicyDefinitionPathMap struct {
	*ygnmi.NodePath
}

// RoutingPolicy_PolicyDefinitionPathMapAny represents the wildcard version of the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition YANG schema element.
type RoutingPolicy_PolicyDefinitionPathMapAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *RoutingPolicy_PolicyDefinitionPathMap) PathOriginName() string {
	return "openconfig"
}

// Name (leaf): Name of the top-level policy definition -- this name
// is used in references to the current policy
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "*/name"
//	Path from root:       "/routing-policy/policy-definitions/policy-definition/*/name"
func (n *RoutingPolicy_PolicyDefinitionPath) Name() *RoutingPolicy_PolicyDefinition_NamePath {
	ps := &RoutingPolicy_PolicyDefinition_NamePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "name"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// Name (leaf): Name of the top-level policy definition -- this name
// is used in references to the current policy
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "*/name"
//	Path from root:       "/routing-policy/policy-definitions/policy-definition/*/name"
func (n *RoutingPolicy_PolicyDefinitionPathAny) Name() *RoutingPolicy_PolicyDefinition_NamePathAny {
	ps := &RoutingPolicy_PolicyDefinition_NamePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "name"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// StatementMap (list): Policy statements group conditions and actions
// within a policy definition.  They are evaluated in
// the order specified (see the description of policy
// evaluation at the top of this module.
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "statements/statement"
//	Path from root:       "/routing-policy/policy-definitions/policy-definition/statements/statement"
func (n *RoutingPolicy_PolicyDefinitionPath) StatementMap() *RoutingPolicy_PolicyDefinition_StatementPathMap {
	ps := &RoutingPolicy_PolicyDefinition_StatementPathMap{
		NodePath: ygnmi.NewNodePath(
			[]string{"statements"},
			map[string]interface{}{},
			n,
		),
	}
	return ps
}

// StatementMap (list): Policy statements group conditions and actions
// within a policy definition.  They are evaluated in
// the order specified (see the description of policy
// evaluation at the top of this module.
//
//	Defining module:      "openconfig-routing-policy"
//	Instantiating module: "openconfig-routing-policy"
//	Path from parent:     "statements/statement"
//	Path from root:       "/routing-policy/policy-definitions/policy-definition/statements/statement"
func (n *RoutingPolicy_PolicyDefinitionPathAny) StatementMap() *RoutingPolicy_PolicyDefinition_StatementPathMapAny {
	ps := &RoutingPolicy_PolicyDefinition_StatementPathMapAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"statements"},
			map[string]interface{}{},
			n,
		),
	}
	return ps
}

// State returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_PolicyDefinitionPath) State() ygnmi.SingletonQuery[*oc.RoutingPolicy_PolicyDefinition] {
	return ygnmi.NewSingletonQuery[*oc.RoutingPolicy_PolicyDefinition](
		"RoutingPolicy_PolicyDefinition",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_PolicyDefinitionPathAny) State() ygnmi.WildcardQuery[*oc.RoutingPolicy_PolicyDefinition] {
	return ygnmi.NewWildcardQuery[*oc.RoutingPolicy_PolicyDefinition](
		"RoutingPolicy_PolicyDefinition",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_PolicyDefinitionPath) Config() ygnmi.ConfigQuery[*oc.RoutingPolicy_PolicyDefinition] {
	return ygnmi.NewConfigQuery[*oc.RoutingPolicy_PolicyDefinition](
		"RoutingPolicy_PolicyDefinition",
		false,
		true,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_PolicyDefinitionPathAny) Config() ygnmi.WildcardQuery[*oc.RoutingPolicy_PolicyDefinition] {
	return ygnmi.NewWildcardQuery[*oc.RoutingPolicy_PolicyDefinition](
		"RoutingPolicy_PolicyDefinition",
		false,
		true,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_PolicyDefinitionPathMap) State() ygnmi.SingletonQuery[map[string]*oc.RoutingPolicy_PolicyDefinition] {
	return ygnmi.NewSingletonQuery[map[string]*oc.RoutingPolicy_PolicyDefinition](
		"RoutingPolicy",
		true,
		false,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[string]*oc.RoutingPolicy_PolicyDefinition, bool) {
			ret := gs.(*oc.RoutingPolicy).PolicyDefinition
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath:  []string{"openconfig-routing-policy:policy-definitions"},
			PostRelPath: []string{"openconfig-routing-policy:policy-definition"},
		},
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_PolicyDefinitionPathMapAny) State() ygnmi.WildcardQuery[map[string]*oc.RoutingPolicy_PolicyDefinition] {
	return ygnmi.NewWildcardQuery[map[string]*oc.RoutingPolicy_PolicyDefinition](
		"RoutingPolicy",
		true,
		false,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[string]*oc.RoutingPolicy_PolicyDefinition, bool) {
			ret := gs.(*oc.RoutingPolicy).PolicyDefinition
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath:  []string{"openconfig-routing-policy:policy-definitions"},
			PostRelPath: []string{"openconfig-routing-policy:policy-definition"},
		},
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_PolicyDefinitionPathMap) Config() ygnmi.ConfigQuery[map[string]*oc.RoutingPolicy_PolicyDefinition] {
	return ygnmi.NewConfigQuery[map[string]*oc.RoutingPolicy_PolicyDefinition](
		"RoutingPolicy",
		false,
		true,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[string]*oc.RoutingPolicy_PolicyDefinition, bool) {
			ret := gs.(*oc.RoutingPolicy).PolicyDefinition
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath:  []string{"openconfig-routing-policy:policy-definitions"},
			PostRelPath: []string{"openconfig-routing-policy:policy-definition"},
		},
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *RoutingPolicy_PolicyDefinitionPathMapAny) Config() ygnmi.WildcardQuery[map[string]*oc.RoutingPolicy_PolicyDefinition] {
	return ygnmi.NewWildcardQuery[map[string]*oc.RoutingPolicy_PolicyDefinition](
		"RoutingPolicy",
		false,
		true,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[string]*oc.RoutingPolicy_PolicyDefinition, bool) {
			ret := gs.(*oc.RoutingPolicy).PolicyDefinition
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.RoutingPolicy) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath:  []string{"openconfig-routing-policy:policy-definitions"},
			PostRelPath: []string{"openconfig-routing-policy:policy-definition"},
		},
	)
}
