/*
Package openconfigbfd is a generated package which contains definitions
of structs which generate gNMI paths for a YANG schema.

This package was generated by ygnmi version: v0.15.0: (ygot: v0.35.0)
using the following YANG input files:
	- ./yang-repo/openconfig/interfaces/openconfig-interfaces.yang
	- ./yang-repo/openconfig/interfaces/openconfig-if-ip.yang
	- ./yang-repo/openconfig/bgp/openconfig-bgp.yang
	- ./yang-repo/openconfig/acl/openconfig-acl.yang
	- ./yang-repo/openconfig/network-instance/openconfig-network-instance.yang
	- ./yang-repo/openconfig/system/openconfig-system.yang
Imported modules were sourced from:
	- ./yang-repo
	- ./yang-repo/iana
	- ./yang-repo/ietf
	- ./yang-repo/mappings
	- ./yang-repo/mappings/openconfig
	- ./yang-repo/openconfig
	- ./yang-repo/openconfig/acl
	- ./yang-repo/openconfig/aft
	- ./yang-repo/openconfig/bfd
	- ./yang-repo/openconfig/bgp
	- ./yang-repo/openconfig/defined-sets
	- ./yang-repo/openconfig/extensions
	- ./yang-repo/openconfig/flex-algo
	- ./yang-repo/openconfig/gnsi
	- ./yang-repo/openconfig/gribi
	- ./yang-repo/openconfig/interfaces
	- ./yang-repo/openconfig/isis
	- ./yang-repo/openconfig/keychain
	- ./yang-repo/openconfig/lacp
	- ./yang-repo/openconfig/lldp
	- ./yang-repo/openconfig/local-routing
	- ./yang-repo/openconfig/mpls
	- ./yang-repo/openconfig/multicast
	- ./yang-repo/openconfig/network-instance
	- ./yang-repo/openconfig/optical-transport
	- ./yang-repo/openconfig/ospf
	- ./yang-repo/openconfig/p4rt
	- ./yang-repo/openconfig/pcep
	- ./yang-repo/openconfig/platform
	- ./yang-repo/openconfig/policy-forwarding
	- ./yang-repo/openconfig/policy
	- ./yang-repo/openconfig/qos
	- ./yang-repo/openconfig/rib
	- ./yang-repo/openconfig/sampling
	- ./yang-repo/openconfig/segment-routing
	- ./yang-repo/openconfig/stp
	- ./yang-repo/openconfig/system
	- ./yang-repo/openconfig/test
	- ./yang-repo/openconfig/types
	- ./yang-repo/openconfig/vlan
	- ./yang-repo/srl_nokia
	- ./yang-repo/srl_nokia/models
	- ./yang-repo/srl_nokia/models/acl
	- ./yang-repo/srl_nokia/models/bfd
	- ./yang-repo/srl_nokia/models/common
	- ./yang-repo/srl_nokia/models/ethcfm
	- ./yang-repo/srl_nokia/models/grpc
	- ./yang-repo/srl_nokia/models/interfaces
	- ./yang-repo/srl_nokia/models/ndk
	- ./yang-repo/srl_nokia/models/network-instance
	- ./yang-repo/srl_nokia/models/oam
	- ./yang-repo/srl_nokia/models/platform
	- ./yang-repo/srl_nokia/models/qos
	- ./yang-repo/srl_nokia/models/routing-policy
	- ./yang-repo/srl_nokia/models/service-activation-testhead
	- ./yang-repo/srl_nokia/models/stp
	- ./yang-repo/srl_nokia/models/subscriber-mgmt
	- ./yang-repo/srl_nokia/models/sync
	- ./yang-repo/srl_nokia/models/system
	- ./yang-repo/srl_nokia/models/transport-security
	- ./yang-repo/srl_nokia/models/tunnel
	- ./yang-repo/srl_nokia/models/twamp
*/
package openconfigbfd

import (
	"reflect"
	oc "github.com/LeBaoTai/SDN-RD/internal/oc"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygnmi/ygnmi"
	"github.com/openconfig/ygot/ytypes"
)

// Bfd_Interface_Peer_SubscribedProtocolsPath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/subscribed-protocols YANG schema element.
type Bfd_Interface_Peer_SubscribedProtocolsPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_SubscribedProtocolsPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/subscribed-protocols YANG schema element.
type Bfd_Interface_Peer_SubscribedProtocolsPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_SubscribedProtocolsPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/subscribed-protocols"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/subscribed-protocols"
func (n *Bfd_Interface_Peer_SubscribedProtocolsPath) State() ygnmi.SingletonQuery[[]oc.E_OpenconfigPolicyTypes_INSTALL_PROTOCOL_TYPE] {
	return ygnmi.NewSingletonQuery[[]oc.E_OpenconfigPolicyTypes_INSTALL_PROTOCOL_TYPE](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "subscribed-protocols"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.E_OpenconfigPolicyTypes_INSTALL_PROTOCOL_TYPE, bool) { 
			ret := gs.(*oc.Bfd_Interface_Peer).SubscribedProtocols
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/subscribed-protocols"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/subscribed-protocols"
func (n *Bfd_Interface_Peer_SubscribedProtocolsPathAny) State() ygnmi.WildcardQuery[[]oc.E_OpenconfigPolicyTypes_INSTALL_PROTOCOL_TYPE] {
	return ygnmi.NewWildcardQuery[[]oc.E_OpenconfigPolicyTypes_INSTALL_PROTOCOL_TYPE](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "subscribed-protocols"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.E_OpenconfigPolicyTypes_INSTALL_PROTOCOL_TYPE, bool) { 
			ret := gs.(*oc.Bfd_Interface_Peer).SubscribedProtocols
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_Peer_UpTransitionsPath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/up-transitions YANG schema element.
type Bfd_Interface_Peer_UpTransitionsPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_UpTransitionsPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/up-transitions YANG schema element.
type Bfd_Interface_Peer_UpTransitionsPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_UpTransitionsPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/up-transitions"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/up-transitions"
func (n *Bfd_Interface_Peer_UpTransitionsPath) State() ygnmi.SingletonQuery[uint64] {
	return ygnmi.NewSingletonQuery[uint64](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "up-transitions"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Bfd_Interface_Peer).UpTransitions
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/up-transitions"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/up-transitions"
func (n *Bfd_Interface_Peer_UpTransitionsPathAny) State() ygnmi.WildcardQuery[uint64] {
	return ygnmi.NewWildcardQuery[uint64](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "up-transitions"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Bfd_Interface_Peer).UpTransitions
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_PeerPath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer YANG schema element.
type Bfd_Interface_PeerPath struct {
	*ygnmi.NodePath
}

// Bfd_Interface_PeerPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer YANG schema element.
type Bfd_Interface_PeerPathAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_PeerPath) PathOriginName() string {
     return "openconfig"
}

// Bfd_Interface_PeerPathMap represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer YANG schema element.
type Bfd_Interface_PeerPathMap struct {
	*ygnmi.NodePath
}

// Bfd_Interface_PeerPathMapAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer YANG schema element.
type Bfd_Interface_PeerPathMapAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_PeerPathMap) PathOriginName() string {
     return "openconfig"
}

// Async (container): Operational state parameters specifically relating to
// asynchronous mode of BFD.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/async"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/async"
func (n *Bfd_Interface_PeerPath) Async() *Bfd_Interface_Peer_AsyncPath {
	ps := &Bfd_Interface_Peer_AsyncPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "async"},
			map[string]interface{}{},
			n,
		),
	}
	return ps
}

// Async (container): Operational state parameters specifically relating to
// asynchronous mode of BFD.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/async"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/async"
func (n *Bfd_Interface_PeerPathAny) Async() *Bfd_Interface_Peer_AsyncPathAny {
	ps := &Bfd_Interface_Peer_AsyncPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "async"},
			map[string]interface{}{},
			n,
		),
	}
	return ps
}

// DemandModeRequested (leaf): This leaf is set to true when the remote system has requested
// demand mode be run for this session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/demand-mode-requested"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/demand-mode-requested"
func (n *Bfd_Interface_PeerPath) DemandModeRequested() *Bfd_Interface_Peer_DemandModeRequestedPath {
	ps := &Bfd_Interface_Peer_DemandModeRequestedPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "demand-mode-requested"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// DemandModeRequested (leaf): This leaf is set to true when the remote system has requested
// demand mode be run for this session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/demand-mode-requested"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/demand-mode-requested"
func (n *Bfd_Interface_PeerPathAny) DemandModeRequested() *Bfd_Interface_Peer_DemandModeRequestedPathAny {
	ps := &Bfd_Interface_Peer_DemandModeRequestedPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "demand-mode-requested"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// Echo (container): Operational state parameters specifically relating to the
// echo mode of BFD.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/echo"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/echo"
func (n *Bfd_Interface_PeerPath) Echo() *Bfd_Interface_Peer_EchoPath {
	ps := &Bfd_Interface_Peer_EchoPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "echo"},
			map[string]interface{}{},
			n,
		),
	}
	return ps
}

// Echo (container): Operational state parameters specifically relating to the
// echo mode of BFD.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/echo"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/echo"
func (n *Bfd_Interface_PeerPathAny) Echo() *Bfd_Interface_Peer_EchoPathAny {
	ps := &Bfd_Interface_Peer_EchoPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "echo"},
			map[string]interface{}{},
			n,
		),
	}
	return ps
}

// FailureTransitions (leaf): The number of times that the BFD session has transitioned
// from the UP state to the DOWN state. This does not include
// UP to ADMIN_DOWN transitions
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/failure-transitions"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/failure-transitions"
func (n *Bfd_Interface_PeerPath) FailureTransitions() *Bfd_Interface_Peer_FailureTransitionsPath {
	ps := &Bfd_Interface_Peer_FailureTransitionsPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "failure-transitions"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// FailureTransitions (leaf): The number of times that the BFD session has transitioned
// from the UP state to the DOWN state. This does not include
// UP to ADMIN_DOWN transitions
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/failure-transitions"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/failure-transitions"
func (n *Bfd_Interface_PeerPathAny) FailureTransitions() *Bfd_Interface_Peer_FailureTransitionsPathAny {
	ps := &Bfd_Interface_Peer_FailureTransitionsPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "failure-transitions"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// LastFailureTime (leaf): The time of the last transition of the BFD session from the UP state
// to the DOWN state, expressed as the number of nanoseconds since
// the Unix epoch. This does not include UP to ADMIN_DOWN transitions
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/last-failure-time"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/last-failure-time"
func (n *Bfd_Interface_PeerPath) LastFailureTime() *Bfd_Interface_Peer_LastFailureTimePath {
	ps := &Bfd_Interface_Peer_LastFailureTimePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "last-failure-time"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// LastFailureTime (leaf): The time of the last transition of the BFD session from the UP state
// to the DOWN state, expressed as the number of nanoseconds since
// the Unix epoch. This does not include UP to ADMIN_DOWN transitions
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/last-failure-time"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/last-failure-time"
func (n *Bfd_Interface_PeerPathAny) LastFailureTime() *Bfd_Interface_Peer_LastFailureTimePathAny {
	ps := &Bfd_Interface_Peer_LastFailureTimePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "last-failure-time"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// LocalAddress (leaf): The IP address used by the local system for this BFD session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/local-address"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/local-address"
func (n *Bfd_Interface_PeerPath) LocalAddress() *Bfd_Interface_Peer_LocalAddressPath {
	ps := &Bfd_Interface_Peer_LocalAddressPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "local-address"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// LocalAddress (leaf): The IP address used by the local system for this BFD session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/local-address"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/local-address"
func (n *Bfd_Interface_PeerPathAny) LocalAddress() *Bfd_Interface_Peer_LocalAddressPathAny {
	ps := &Bfd_Interface_Peer_LocalAddressPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "local-address"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// LocalDiagnosticCode (leaf): The local BFD diagnostic code indicating the most recent
// reason for failure of this BFD session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/local-diagnostic-code"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/local-diagnostic-code"
func (n *Bfd_Interface_PeerPath) LocalDiagnosticCode() *Bfd_Interface_Peer_LocalDiagnosticCodePath {
	ps := &Bfd_Interface_Peer_LocalDiagnosticCodePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "local-diagnostic-code"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// LocalDiagnosticCode (leaf): The local BFD diagnostic code indicating the most recent
// reason for failure of this BFD session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/local-diagnostic-code"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/local-diagnostic-code"
func (n *Bfd_Interface_PeerPathAny) LocalDiagnosticCode() *Bfd_Interface_Peer_LocalDiagnosticCodePathAny {
	ps := &Bfd_Interface_Peer_LocalDiagnosticCodePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "local-diagnostic-code"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// LocalDiscriminator (leaf): A unique identifier used by the local system to identify this
// BFD session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "*/local-discriminator"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/*/local-discriminator"
func (n *Bfd_Interface_PeerPath) LocalDiscriminator() *Bfd_Interface_Peer_LocalDiscriminatorPath {
	ps := &Bfd_Interface_Peer_LocalDiscriminatorPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "local-discriminator"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// LocalDiscriminator (leaf): A unique identifier used by the local system to identify this
// BFD session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "*/local-discriminator"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/*/local-discriminator"
func (n *Bfd_Interface_PeerPathAny) LocalDiscriminator() *Bfd_Interface_Peer_LocalDiscriminatorPathAny {
	ps := &Bfd_Interface_Peer_LocalDiscriminatorPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"*", "local-discriminator"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteAddress (leaf): The IP address used by the remote system for this BFD session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-address"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-address"
func (n *Bfd_Interface_PeerPath) RemoteAddress() *Bfd_Interface_Peer_RemoteAddressPath {
	ps := &Bfd_Interface_Peer_RemoteAddressPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-address"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteAddress (leaf): The IP address used by the remote system for this BFD session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-address"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-address"
func (n *Bfd_Interface_PeerPathAny) RemoteAddress() *Bfd_Interface_Peer_RemoteAddressPathAny {
	ps := &Bfd_Interface_Peer_RemoteAddressPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-address"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteAuthenticationEnabled (leaf): This leaf is set to true when the remote system has specified
// that authentication is present for the BFD session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-authentication-enabled"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-authentication-enabled"
func (n *Bfd_Interface_PeerPath) RemoteAuthenticationEnabled() *Bfd_Interface_Peer_RemoteAuthenticationEnabledPath {
	ps := &Bfd_Interface_Peer_RemoteAuthenticationEnabledPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-authentication-enabled"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteAuthenticationEnabled (leaf): This leaf is set to true when the remote system has specified
// that authentication is present for the BFD session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-authentication-enabled"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-authentication-enabled"
func (n *Bfd_Interface_PeerPathAny) RemoteAuthenticationEnabled() *Bfd_Interface_Peer_RemoteAuthenticationEnabledPathAny {
	ps := &Bfd_Interface_Peer_RemoteAuthenticationEnabledPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-authentication-enabled"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteControlPlaneIndependent (leaf): This leaf is set to true when the remote system has specified
// that the hardware implementing this BFD session is independent
// of the control plane's liveliness.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-control-plane-independent"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-control-plane-independent"
func (n *Bfd_Interface_PeerPath) RemoteControlPlaneIndependent() *Bfd_Interface_Peer_RemoteControlPlaneIndependentPath {
	ps := &Bfd_Interface_Peer_RemoteControlPlaneIndependentPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-control-plane-independent"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteControlPlaneIndependent (leaf): This leaf is set to true when the remote system has specified
// that the hardware implementing this BFD session is independent
// of the control plane's liveliness.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-control-plane-independent"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-control-plane-independent"
func (n *Bfd_Interface_PeerPathAny) RemoteControlPlaneIndependent() *Bfd_Interface_Peer_RemoteControlPlaneIndependentPathAny {
	ps := &Bfd_Interface_Peer_RemoteControlPlaneIndependentPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-control-plane-independent"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteDiagnosticCode (leaf): The remote BFD diagnostic code indicating the remote system's
// reason for failure of the BFD session
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-diagnostic-code"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-diagnostic-code"
func (n *Bfd_Interface_PeerPath) RemoteDiagnosticCode() *Bfd_Interface_Peer_RemoteDiagnosticCodePath {
	ps := &Bfd_Interface_Peer_RemoteDiagnosticCodePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-diagnostic-code"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteDiagnosticCode (leaf): The remote BFD diagnostic code indicating the remote system's
// reason for failure of the BFD session
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-diagnostic-code"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-diagnostic-code"
func (n *Bfd_Interface_PeerPathAny) RemoteDiagnosticCode() *Bfd_Interface_Peer_RemoteDiagnosticCodePathAny {
	ps := &Bfd_Interface_Peer_RemoteDiagnosticCodePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-diagnostic-code"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteDiscriminator (leaf): A unique identified used by the remote system to identify this
// BFD session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-discriminator"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-discriminator"
func (n *Bfd_Interface_PeerPath) RemoteDiscriminator() *Bfd_Interface_Peer_RemoteDiscriminatorPath {
	ps := &Bfd_Interface_Peer_RemoteDiscriminatorPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-discriminator"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteDiscriminator (leaf): A unique identified used by the remote system to identify this
// BFD session.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-discriminator"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-discriminator"
func (n *Bfd_Interface_PeerPathAny) RemoteDiscriminator() *Bfd_Interface_Peer_RemoteDiscriminatorPathAny {
	ps := &Bfd_Interface_Peer_RemoteDiscriminatorPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-discriminator"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteMinimumReceiveInterval (leaf): The value of the minimum receive interval that was specified
// in the most recent BFD control packet received from the peer.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-minimum-receive-interval"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-minimum-receive-interval"
func (n *Bfd_Interface_PeerPath) RemoteMinimumReceiveInterval() *Bfd_Interface_Peer_RemoteMinimumReceiveIntervalPath {
	ps := &Bfd_Interface_Peer_RemoteMinimumReceiveIntervalPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-minimum-receive-interval"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteMinimumReceiveInterval (leaf): The value of the minimum receive interval that was specified
// in the most recent BFD control packet received from the peer.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-minimum-receive-interval"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-minimum-receive-interval"
func (n *Bfd_Interface_PeerPathAny) RemoteMinimumReceiveInterval() *Bfd_Interface_Peer_RemoteMinimumReceiveIntervalPathAny {
	ps := &Bfd_Interface_Peer_RemoteMinimumReceiveIntervalPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-minimum-receive-interval"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteSessionState (leaf): The reported state of the BFD session according to the remote
// system. This state reflects the last state reported in a BFD
// control packet.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-session-state"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-session-state"
func (n *Bfd_Interface_PeerPath) RemoteSessionState() *Bfd_Interface_Peer_RemoteSessionStatePath {
	ps := &Bfd_Interface_Peer_RemoteSessionStatePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-session-state"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// RemoteSessionState (leaf): The reported state of the BFD session according to the remote
// system. This state reflects the last state reported in a BFD
// control packet.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/remote-session-state"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-session-state"
func (n *Bfd_Interface_PeerPathAny) RemoteSessionState() *Bfd_Interface_Peer_RemoteSessionStatePathAny {
	ps := &Bfd_Interface_Peer_RemoteSessionStatePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "remote-session-state"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// SessionState (leaf): The state of the BFD session perceived by the local system.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/session-state"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/session-state"
func (n *Bfd_Interface_PeerPath) SessionState() *Bfd_Interface_Peer_SessionStatePath {
	ps := &Bfd_Interface_Peer_SessionStatePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "session-state"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// SessionState (leaf): The state of the BFD session perceived by the local system.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/session-state"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/session-state"
func (n *Bfd_Interface_PeerPathAny) SessionState() *Bfd_Interface_Peer_SessionStatePathAny {
	ps := &Bfd_Interface_Peer_SessionStatePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "session-state"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// SubscribedProtocols (leaf-list): Indicates the set of protocols that currently use
// this BFD session for liveliness detection.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/subscribed-protocols"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/subscribed-protocols"
func (n *Bfd_Interface_PeerPath) SubscribedProtocols() *Bfd_Interface_Peer_SubscribedProtocolsPath {
	ps := &Bfd_Interface_Peer_SubscribedProtocolsPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "subscribed-protocols"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// SubscribedProtocols (leaf-list): Indicates the set of protocols that currently use
// this BFD session for liveliness detection.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/subscribed-protocols"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/subscribed-protocols"
func (n *Bfd_Interface_PeerPathAny) SubscribedProtocols() *Bfd_Interface_Peer_SubscribedProtocolsPathAny {
	ps := &Bfd_Interface_Peer_SubscribedProtocolsPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "subscribed-protocols"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// UpTransitions (leaf): The number of times that the adjacency with the neighbor
// // TODO: looks to only be supported in SROS
// has transitioned into the up state.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/up-transitions"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/up-transitions"
func (n *Bfd_Interface_PeerPath) UpTransitions() *Bfd_Interface_Peer_UpTransitionsPath {
	ps := &Bfd_Interface_Peer_UpTransitionsPath{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "up-transitions"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// UpTransitions (leaf): The number of times that the adjacency with the neighbor
// // TODO: looks to only be supported in SROS
// has transitioned into the up state.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/up-transitions"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/up-transitions"
func (n *Bfd_Interface_PeerPathAny) UpTransitions() *Bfd_Interface_Peer_UpTransitionsPathAny {
	ps := &Bfd_Interface_Peer_UpTransitionsPathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"state", "up-transitions"},
			map[string]interface{}{},
			n,
		),
		parent: n,
	}
	return ps
}

// State returns a Query that can be used in gNMI operations.
func (n *Bfd_Interface_PeerPath) State() ygnmi.SingletonQuery[*oc.Bfd_Interface_Peer] {
	return ygnmi.NewSingletonQuery[*oc.Bfd_Interface_Peer](
		"Bfd_Interface_Peer",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *Bfd_Interface_PeerPathAny) State() ygnmi.WildcardQuery[*oc.Bfd_Interface_Peer] {
	return ygnmi.NewWildcardQuery[*oc.Bfd_Interface_Peer](
		"Bfd_Interface_Peer",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *Bfd_Interface_PeerPathMap) State() ygnmi.SingletonQuery[map[string]*oc.Bfd_Interface_Peer] {
	return ygnmi.NewSingletonQuery[map[string]*oc.Bfd_Interface_Peer](
		"Bfd_Interface",
		true,
		false,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[string]*oc.Bfd_Interface_Peer, bool) { 
			ret := gs.(*oc.Bfd_Interface).Peer
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath: []string{"openconfig-bfd:peers"},
			PostRelPath: []string{"openconfig-bfd:peer"},
		},
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *Bfd_Interface_PeerPathMapAny) State() ygnmi.WildcardQuery[map[string]*oc.Bfd_Interface_Peer] {
	return ygnmi.NewWildcardQuery[map[string]*oc.Bfd_Interface_Peer](
		"Bfd_Interface",
		true,
		false,
		false,
		false,
		true,
		true,
		n,
		func(gs ygot.ValidatedGoStruct) (map[string]*oc.Bfd_Interface_Peer, bool) { 
			ret := gs.(*oc.Bfd_Interface).Peer
			return ret, ret != nil
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		&ygnmi.CompressionInfo{
			PreRelPath: []string{"openconfig-bfd:peers"},
			PostRelPath: []string{"openconfig-bfd:peer"},
		},
	)
}

// Bfd_Interface_Peer_Async_LastPacketReceivedPath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/async/last-packet-received YANG schema element.
type Bfd_Interface_Peer_Async_LastPacketReceivedPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_Async_LastPacketReceivedPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/async/last-packet-received YANG schema element.
type Bfd_Interface_Peer_Async_LastPacketReceivedPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_Async_LastPacketReceivedPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "last-packet-received"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/async/last-packet-received"
func (n *Bfd_Interface_Peer_Async_LastPacketReceivedPath) State() ygnmi.SingletonQuery[uint64] {
	return ygnmi.NewSingletonQuery[uint64](
		"Bfd_Interface_Peer_Async",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"last-packet-received"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Bfd_Interface_Peer_Async).LastPacketReceived
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer_Async) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "last-packet-received"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/async/last-packet-received"
func (n *Bfd_Interface_Peer_Async_LastPacketReceivedPathAny) State() ygnmi.WildcardQuery[uint64] {
	return ygnmi.NewWildcardQuery[uint64](
		"Bfd_Interface_Peer_Async",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"last-packet-received"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Bfd_Interface_Peer_Async).LastPacketReceived
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer_Async) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_Peer_Async_LastPacketTransmittedPath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/async/last-packet-transmitted YANG schema element.
type Bfd_Interface_Peer_Async_LastPacketTransmittedPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_Async_LastPacketTransmittedPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/async/last-packet-transmitted YANG schema element.
type Bfd_Interface_Peer_Async_LastPacketTransmittedPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_Async_LastPacketTransmittedPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "last-packet-transmitted"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/async/last-packet-transmitted"
func (n *Bfd_Interface_Peer_Async_LastPacketTransmittedPath) State() ygnmi.SingletonQuery[uint64] {
	return ygnmi.NewSingletonQuery[uint64](
		"Bfd_Interface_Peer_Async",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"last-packet-transmitted"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Bfd_Interface_Peer_Async).LastPacketTransmitted
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer_Async) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "last-packet-transmitted"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/async/last-packet-transmitted"
func (n *Bfd_Interface_Peer_Async_LastPacketTransmittedPathAny) State() ygnmi.WildcardQuery[uint64] {
	return ygnmi.NewWildcardQuery[uint64](
		"Bfd_Interface_Peer_Async",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"last-packet-transmitted"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Bfd_Interface_Peer_Async).LastPacketTransmitted
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer_Async) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_Peer_Async_ReceivedPacketsPath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/async/received-packets YANG schema element.
type Bfd_Interface_Peer_Async_ReceivedPacketsPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_Async_ReceivedPacketsPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/async/received-packets YANG schema element.
type Bfd_Interface_Peer_Async_ReceivedPacketsPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_Async_ReceivedPacketsPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "received-packets"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/async/received-packets"
func (n *Bfd_Interface_Peer_Async_ReceivedPacketsPath) State() ygnmi.SingletonQuery[uint64] {
	return ygnmi.NewSingletonQuery[uint64](
		"Bfd_Interface_Peer_Async",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"received-packets"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Bfd_Interface_Peer_Async).ReceivedPackets
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer_Async) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "received-packets"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/async/received-packets"
func (n *Bfd_Interface_Peer_Async_ReceivedPacketsPathAny) State() ygnmi.WildcardQuery[uint64] {
	return ygnmi.NewWildcardQuery[uint64](
		"Bfd_Interface_Peer_Async",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"received-packets"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Bfd_Interface_Peer_Async).ReceivedPackets
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer_Async) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_Peer_Async_TransmittedPacketsPath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/async/transmitted-packets YANG schema element.
type Bfd_Interface_Peer_Async_TransmittedPacketsPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_Async_TransmittedPacketsPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/async/transmitted-packets YANG schema element.
type Bfd_Interface_Peer_Async_TransmittedPacketsPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_Async_TransmittedPacketsPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "transmitted-packets"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/async/transmitted-packets"
func (n *Bfd_Interface_Peer_Async_TransmittedPacketsPath) State() ygnmi.SingletonQuery[uint64] {
	return ygnmi.NewSingletonQuery[uint64](
		"Bfd_Interface_Peer_Async",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"transmitted-packets"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Bfd_Interface_Peer_Async).TransmittedPackets
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer_Async) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "transmitted-packets"
// 	Path from root:       "/bfd/interfaces/interface/peers/peer/state/async/transmitted-packets"
func (n *Bfd_Interface_Peer_Async_TransmittedPacketsPathAny) State() ygnmi.WildcardQuery[uint64] {
	return ygnmi.NewWildcardQuery[uint64](
		"Bfd_Interface_Peer_Async",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"transmitted-packets"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint64, bool) { 
			ret := gs.(*oc.Bfd_Interface_Peer_Async).TransmittedPackets
			if ret == nil {
				var zero uint64
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer_Async) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}
