/*
Package openconfigbfd is a generated package which contains definitions
of structs which generate gNMI paths for a YANG schema.

This package was generated by ygnmi version: v0.15.0: (ygot: v0.35.0)
using the following YANG input files:
	- ./yang-repo/openconfig/interfaces/openconfig-interfaces.yang
	- ./yang-repo/openconfig/interfaces/openconfig-if-ip.yang
	- ./yang-repo/openconfig/bgp/openconfig-bgp.yang
	- ./yang-repo/openconfig/acl/openconfig-acl.yang
	- ./yang-repo/openconfig/network-instance/openconfig-network-instance.yang
	- ./yang-repo/openconfig/system/openconfig-system.yang
Imported modules were sourced from:
	- ./yang-repo
	- ./yang-repo/iana
	- ./yang-repo/ietf
	- ./yang-repo/mappings
	- ./yang-repo/mappings/openconfig
	- ./yang-repo/openconfig
	- ./yang-repo/openconfig/acl
	- ./yang-repo/openconfig/aft
	- ./yang-repo/openconfig/bfd
	- ./yang-repo/openconfig/bgp
	- ./yang-repo/openconfig/defined-sets
	- ./yang-repo/openconfig/extensions
	- ./yang-repo/openconfig/flex-algo
	- ./yang-repo/openconfig/gnsi
	- ./yang-repo/openconfig/gribi
	- ./yang-repo/openconfig/interfaces
	- ./yang-repo/openconfig/isis
	- ./yang-repo/openconfig/keychain
	- ./yang-repo/openconfig/lacp
	- ./yang-repo/openconfig/lldp
	- ./yang-repo/openconfig/local-routing
	- ./yang-repo/openconfig/mpls
	- ./yang-repo/openconfig/multicast
	- ./yang-repo/openconfig/network-instance
	- ./yang-repo/openconfig/optical-transport
	- ./yang-repo/openconfig/ospf
	- ./yang-repo/openconfig/p4rt
	- ./yang-repo/openconfig/pcep
	- ./yang-repo/openconfig/platform
	- ./yang-repo/openconfig/policy-forwarding
	- ./yang-repo/openconfig/policy
	- ./yang-repo/openconfig/qos
	- ./yang-repo/openconfig/rib
	- ./yang-repo/openconfig/sampling
	- ./yang-repo/openconfig/segment-routing
	- ./yang-repo/openconfig/stp
	- ./yang-repo/openconfig/system
	- ./yang-repo/openconfig/test
	- ./yang-repo/openconfig/types
	- ./yang-repo/openconfig/vlan
	- ./yang-repo/srl_nokia
	- ./yang-repo/srl_nokia/models
	- ./yang-repo/srl_nokia/models/acl
	- ./yang-repo/srl_nokia/models/bfd
	- ./yang-repo/srl_nokia/models/common
	- ./yang-repo/srl_nokia/models/ethcfm
	- ./yang-repo/srl_nokia/models/grpc
	- ./yang-repo/srl_nokia/models/interfaces
	- ./yang-repo/srl_nokia/models/ndk
	- ./yang-repo/srl_nokia/models/network-instance
	- ./yang-repo/srl_nokia/models/oam
	- ./yang-repo/srl_nokia/models/platform
	- ./yang-repo/srl_nokia/models/qos
	- ./yang-repo/srl_nokia/models/routing-policy
	- ./yang-repo/srl_nokia/models/service-activation-testhead
	- ./yang-repo/srl_nokia/models/stp
	- ./yang-repo/srl_nokia/models/subscriber-mgmt
	- ./yang-repo/srl_nokia/models/sync
	- ./yang-repo/srl_nokia/models/system
	- ./yang-repo/srl_nokia/models/transport-security
	- ./yang-repo/srl_nokia/models/tunnel
	- ./yang-repo/srl_nokia/models/twamp
*/
package openconfigbfd

import (
	"reflect"
	oc "github.com/LeBaoTai/SDN-RD/internal/oc"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygnmi/ygnmi"
	"github.com/openconfig/ygot/ytypes"
)

// BfdPath represents the /openconfig-bfd/bfd YANG schema element.
type BfdPath struct {
	*ygnmi.NodePath
}

// BfdPathAny represents the wildcard version of the /openconfig-bfd/bfd YANG schema element.
type BfdPathAny struct {
	*ygnmi.NodePath
}

// PathOrigin returns the name of the origin for the path object.
func (n *BfdPath) PathOriginName() string {
     return "openconfig"
}

// InterfaceAny (list): Per-interface configuration and state parameters for BFD.
// The interface referenced is based on the interface and
// subinterface leaves within the interface-ref container -
// which reference an entry in the /interfaces/interface list -
// and should not rely on the value of the list key.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "interfaces/interface"
// 	Path from root:       "/bfd/interfaces/interface"
func (n *BfdPath) InterfaceAny() *Bfd_InterfacePathAny {
	ps := &Bfd_InterfacePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"interfaces", "interface"},
			map[string]interface{}{"id": "*"},
			n,
		),
	}
	return ps
}

// InterfaceAny (list): Per-interface configuration and state parameters for BFD.
// The interface referenced is based on the interface and
// subinterface leaves within the interface-ref container -
// which reference an entry in the /interfaces/interface list -
// and should not rely on the value of the list key.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "interfaces/interface"
// 	Path from root:       "/bfd/interfaces/interface"
func (n *BfdPathAny) InterfaceAny() *Bfd_InterfacePathAny {
	ps := &Bfd_InterfacePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"interfaces", "interface"},
			map[string]interface{}{"id": "*"},
			n,
		),
	}
	return ps
}

// Interface (list): Per-interface configuration and state parameters for BFD.
// The interface referenced is based on the interface and
// subinterface leaves within the interface-ref container -
// which reference an entry in the /interfaces/interface list -
// and should not rely on the value of the list key.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "interfaces/interface"
// 	Path from root:       "/bfd/interfaces/interface"
//
// 	Id: string
func (n *BfdPath) Interface(Id string) *Bfd_InterfacePath {
	ps := &Bfd_InterfacePath{
		NodePath: ygnmi.NewNodePath(
			[]string{"interfaces", "interface"},
			map[string]interface{}{"id": Id},
			n,
		),
	}
	return ps
}

// Interface (list): Per-interface configuration and state parameters for BFD.
// The interface referenced is based on the interface and
// subinterface leaves within the interface-ref container -
// which reference an entry in the /interfaces/interface list -
// and should not rely on the value of the list key.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "interfaces/interface"
// 	Path from root:       "/bfd/interfaces/interface"
//
// 	Id: string
func (n *BfdPathAny) Interface(Id string) *Bfd_InterfacePathAny {
	ps := &Bfd_InterfacePathAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"interfaces", "interface"},
			map[string]interface{}{"id": Id},
			n,
		),
	}
	return ps
}

// InterfaceMap (list): Per-interface configuration and state parameters for BFD.
// The interface referenced is based on the interface and
// subinterface leaves within the interface-ref container -
// which reference an entry in the /interfaces/interface list -
// and should not rely on the value of the list key.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "interfaces/interface"
// 	Path from root:       "/bfd/interfaces/interface"
func (n *BfdPath) InterfaceMap() *Bfd_InterfacePathMap {
	ps := &Bfd_InterfacePathMap{
		NodePath: ygnmi.NewNodePath(
			[]string{"interfaces"},
			map[string]interface{}{},
			n,
		),
	}
	return ps
}

// InterfaceMap (list): Per-interface configuration and state parameters for BFD.
// The interface referenced is based on the interface and
// subinterface leaves within the interface-ref container -
// which reference an entry in the /interfaces/interface list -
// and should not rely on the value of the list key.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "interfaces/interface"
// 	Path from root:       "/bfd/interfaces/interface"
func (n *BfdPathAny) InterfaceMap() *Bfd_InterfacePathMapAny {
	ps := &Bfd_InterfacePathMapAny{
		NodePath: ygnmi.NewNodePath(
			[]string{"interfaces"},
			map[string]interface{}{},
			n,
		),
	}
	return ps
}

func binarySliceToFloatSlice(in []oc.Binary) []float32 {
	converted := make([]float32, 0, len(in))
	for _, binary := range in {
		converted = append(converted, ygot.BinaryToFloat32(binary))
	}
	return converted
}

// State returns a Query that can be used in gNMI operations.
func (n *BfdPath) State() ygnmi.SingletonQuery[*oc.Bfd] {
	return ygnmi.NewSingletonQuery[*oc.Bfd](
		"Bfd",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
func (n *BfdPathAny) State() ygnmi.WildcardQuery[*oc.Bfd] {
	return ygnmi.NewWildcardQuery[*oc.Bfd](
		"Bfd",
		true,
		false,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *BfdPath) Config() ygnmi.ConfigQuery[*oc.Bfd] {
	return ygnmi.NewConfigQuery[*oc.Bfd](
		"Bfd",
		false,
		true,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
func (n *BfdPathAny) Config() ygnmi.WildcardQuery[*oc.Bfd] {
	return ygnmi.NewWildcardQuery[*oc.Bfd](
		"Bfd",
		false,
		true,
		false,
		false,
		true,
		false,
		n,
		nil,
		nil,
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_DesiredMinimumTxIntervalPath represents the /openconfig-bfd/bfd/interfaces/interface/state/desired-minimum-tx-interval YANG schema element.
type Bfd_Interface_DesiredMinimumTxIntervalPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_DesiredMinimumTxIntervalPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/state/desired-minimum-tx-interval YANG schema element.
type Bfd_Interface_DesiredMinimumTxIntervalPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_DesiredMinimumTxIntervalPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/desired-minimum-tx-interval"
// 	Path from root:       "/bfd/interfaces/interface/state/desired-minimum-tx-interval"
func (n *Bfd_Interface_DesiredMinimumTxIntervalPath) State() ygnmi.SingletonQuery[uint32] {
	return ygnmi.NewSingletonQuery[uint32](
		"Bfd_Interface",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "desired-minimum-tx-interval"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) { 
			ret := gs.(*oc.Bfd_Interface).DesiredMinimumTxInterval
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/desired-minimum-tx-interval"
// 	Path from root:       "/bfd/interfaces/interface/state/desired-minimum-tx-interval"
func (n *Bfd_Interface_DesiredMinimumTxIntervalPathAny) State() ygnmi.WildcardQuery[uint32] {
	return ygnmi.NewWildcardQuery[uint32](
		"Bfd_Interface",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "desired-minimum-tx-interval"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) { 
			ret := gs.(*oc.Bfd_Interface).DesiredMinimumTxInterval
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "config/desired-minimum-tx-interval"
// 	Path from root:       "/bfd/interfaces/interface/config/desired-minimum-tx-interval"
func (n *Bfd_Interface_DesiredMinimumTxIntervalPath) Config() ygnmi.ConfigQuery[uint32] {
	return ygnmi.NewConfigQuery[uint32](
		"Bfd_Interface",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "desired-minimum-tx-interval"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) { 
			ret := gs.(*oc.Bfd_Interface).DesiredMinimumTxInterval
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "config/desired-minimum-tx-interval"
// 	Path from root:       "/bfd/interfaces/interface/config/desired-minimum-tx-interval"
func (n *Bfd_Interface_DesiredMinimumTxIntervalPathAny) Config() ygnmi.WildcardQuery[uint32] {
	return ygnmi.NewWildcardQuery[uint32](
		"Bfd_Interface",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "desired-minimum-tx-interval"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) { 
			ret := gs.(*oc.Bfd_Interface).DesiredMinimumTxInterval
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_DetectionMultiplierPath represents the /openconfig-bfd/bfd/interfaces/interface/state/detection-multiplier YANG schema element.
type Bfd_Interface_DetectionMultiplierPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_DetectionMultiplierPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/state/detection-multiplier YANG schema element.
type Bfd_Interface_DetectionMultiplierPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_DetectionMultiplierPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/detection-multiplier"
// 	Path from root:       "/bfd/interfaces/interface/state/detection-multiplier"
func (n *Bfd_Interface_DetectionMultiplierPath) State() ygnmi.SingletonQuery[uint8] {
	return ygnmi.NewSingletonQuery[uint8](
		"Bfd_Interface",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "detection-multiplier"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Bfd_Interface).DetectionMultiplier
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/detection-multiplier"
// 	Path from root:       "/bfd/interfaces/interface/state/detection-multiplier"
func (n *Bfd_Interface_DetectionMultiplierPathAny) State() ygnmi.WildcardQuery[uint8] {
	return ygnmi.NewWildcardQuery[uint8](
		"Bfd_Interface",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "detection-multiplier"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Bfd_Interface).DetectionMultiplier
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "config/detection-multiplier"
// 	Path from root:       "/bfd/interfaces/interface/config/detection-multiplier"
func (n *Bfd_Interface_DetectionMultiplierPath) Config() ygnmi.ConfigQuery[uint8] {
	return ygnmi.NewConfigQuery[uint8](
		"Bfd_Interface",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "detection-multiplier"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Bfd_Interface).DetectionMultiplier
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "config/detection-multiplier"
// 	Path from root:       "/bfd/interfaces/interface/config/detection-multiplier"
func (n *Bfd_Interface_DetectionMultiplierPathAny) Config() ygnmi.WildcardQuery[uint8] {
	return ygnmi.NewWildcardQuery[uint8](
		"Bfd_Interface",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "detection-multiplier"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint8, bool) { 
			ret := gs.(*oc.Bfd_Interface).DetectionMultiplier
			if ret == nil {
				var zero uint8
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_EnablePerMemberLinkPath represents the /openconfig-bfd/bfd/interfaces/interface/state/enable-per-member-link YANG schema element.
type Bfd_Interface_EnablePerMemberLinkPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_EnablePerMemberLinkPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/state/enable-per-member-link YANG schema element.
type Bfd_Interface_EnablePerMemberLinkPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_EnablePerMemberLinkPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/enable-per-member-link"
// 	Path from root:       "/bfd/interfaces/interface/state/enable-per-member-link"
func (n *Bfd_Interface_EnablePerMemberLinkPath) State() ygnmi.SingletonQuery[bool] {
	return ygnmi.NewSingletonQuery[bool](
		"Bfd_Interface",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "enable-per-member-link"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (bool, bool) { 
			ret := gs.(*oc.Bfd_Interface).EnablePerMemberLink
			if ret == nil {
				var zero bool
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/enable-per-member-link"
// 	Path from root:       "/bfd/interfaces/interface/state/enable-per-member-link"
func (n *Bfd_Interface_EnablePerMemberLinkPathAny) State() ygnmi.WildcardQuery[bool] {
	return ygnmi.NewWildcardQuery[bool](
		"Bfd_Interface",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "enable-per-member-link"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (bool, bool) { 
			ret := gs.(*oc.Bfd_Interface).EnablePerMemberLink
			if ret == nil {
				var zero bool
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "config/enable-per-member-link"
// 	Path from root:       "/bfd/interfaces/interface/config/enable-per-member-link"
func (n *Bfd_Interface_EnablePerMemberLinkPath) Config() ygnmi.ConfigQuery[bool] {
	return ygnmi.NewConfigQuery[bool](
		"Bfd_Interface",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "enable-per-member-link"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (bool, bool) { 
			ret := gs.(*oc.Bfd_Interface).EnablePerMemberLink
			if ret == nil {
				var zero bool
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "config/enable-per-member-link"
// 	Path from root:       "/bfd/interfaces/interface/config/enable-per-member-link"
func (n *Bfd_Interface_EnablePerMemberLinkPathAny) Config() ygnmi.WildcardQuery[bool] {
	return ygnmi.NewWildcardQuery[bool](
		"Bfd_Interface",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "enable-per-member-link"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (bool, bool) { 
			ret := gs.(*oc.Bfd_Interface).EnablePerMemberLink
			if ret == nil {
				var zero bool
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_EnabledPath represents the /openconfig-bfd/bfd/interfaces/interface/state/enabled YANG schema element.
type Bfd_Interface_EnabledPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_EnabledPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/state/enabled YANG schema element.
type Bfd_Interface_EnabledPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_EnabledPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/enabled"
// 	Path from root:       "/bfd/interfaces/interface/state/enabled"
func (n *Bfd_Interface_EnabledPath) State() ygnmi.SingletonQuery[bool] {
	return ygnmi.NewSingletonQuery[bool](
		"Bfd_Interface",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "enabled"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (bool, bool) { 
			ret := gs.(*oc.Bfd_Interface).Enabled
			if ret == nil {
				var zero bool
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/enabled"
// 	Path from root:       "/bfd/interfaces/interface/state/enabled"
func (n *Bfd_Interface_EnabledPathAny) State() ygnmi.WildcardQuery[bool] {
	return ygnmi.NewWildcardQuery[bool](
		"Bfd_Interface",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "enabled"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (bool, bool) { 
			ret := gs.(*oc.Bfd_Interface).Enabled
			if ret == nil {
				var zero bool
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "config/enabled"
// 	Path from root:       "/bfd/interfaces/interface/config/enabled"
func (n *Bfd_Interface_EnabledPath) Config() ygnmi.ConfigQuery[bool] {
	return ygnmi.NewConfigQuery[bool](
		"Bfd_Interface",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "enabled"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (bool, bool) { 
			ret := gs.(*oc.Bfd_Interface).Enabled
			if ret == nil {
				var zero bool
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "config/enabled"
// 	Path from root:       "/bfd/interfaces/interface/config/enabled"
func (n *Bfd_Interface_EnabledPathAny) Config() ygnmi.WildcardQuery[bool] {
	return ygnmi.NewWildcardQuery[bool](
		"Bfd_Interface",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "enabled"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (bool, bool) { 
			ret := gs.(*oc.Bfd_Interface).Enabled
			if ret == nil {
				var zero bool
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_IdPath represents the /openconfig-bfd/bfd/interfaces/interface/state/id YANG schema element.
type Bfd_Interface_IdPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_IdPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/state/id YANG schema element.
type Bfd_Interface_IdPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_IdPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/id"
// 	Path from root:       "/bfd/interfaces/interface/state/id"
func (n *Bfd_Interface_IdPath) State() ygnmi.SingletonQuery[string] {
	return ygnmi.NewSingletonQuery[string](
		"Bfd_Interface",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "id"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Bfd_Interface).Id
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/id"
// 	Path from root:       "/bfd/interfaces/interface/state/id"
func (n *Bfd_Interface_IdPathAny) State() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Bfd_Interface",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "id"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Bfd_Interface).Id
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "config/id"
// 	Path from root:       "/bfd/interfaces/interface/config/id"
func (n *Bfd_Interface_IdPath) Config() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"Bfd_Interface",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "id"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Bfd_Interface).Id
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "config/id"
// 	Path from root:       "/bfd/interfaces/interface/config/id"
func (n *Bfd_Interface_IdPathAny) Config() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Bfd_Interface",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "id"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Bfd_Interface).Id
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_LocalAddressPath represents the /openconfig-bfd/bfd/interfaces/interface/state/local-address YANG schema element.
type Bfd_Interface_LocalAddressPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_LocalAddressPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/state/local-address YANG schema element.
type Bfd_Interface_LocalAddressPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_LocalAddressPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/local-address"
// 	Path from root:       "/bfd/interfaces/interface/state/local-address"
func (n *Bfd_Interface_LocalAddressPath) State() ygnmi.SingletonQuery[string] {
	return ygnmi.NewSingletonQuery[string](
		"Bfd_Interface",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "local-address"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Bfd_Interface).LocalAddress
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "state/local-address"
// 	Path from root:       "/bfd/interfaces/interface/state/local-address"
func (n *Bfd_Interface_LocalAddressPathAny) State() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Bfd_Interface",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "local-address"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Bfd_Interface).LocalAddress
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "config/local-address"
// 	Path from root:       "/bfd/interfaces/interface/config/local-address"
func (n *Bfd_Interface_LocalAddressPath) Config() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"Bfd_Interface",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "local-address"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Bfd_Interface).LocalAddress
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-bfd"
// 	Instantiating module: "openconfig-bfd"
// 	Path from parent:     "config/local-address"
// 	Path from root:       "/bfd/interfaces/interface/config/local-address"
func (n *Bfd_Interface_LocalAddressPathAny) Config() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Bfd_Interface",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "local-address"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.Bfd_Interface).LocalAddress
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}
