/*
Package openconfigbfd is a generated package which contains definitions
of structs which generate gNMI paths for a YANG schema.

This package was generated by ygnmi version: v0.15.0: (ygot: v0.35.0)
using the following YANG input files:
  - ./yang-repo/openconfig/interfaces/openconfig-interfaces.yang
  - ./yang-repo/openconfig/interfaces/openconfig-if-ip.yang
  - ./yang-repo/openconfig/bgp/openconfig-bgp.yang
  - ./yang-repo/openconfig/acl/openconfig-acl.yang
  - ./yang-repo/openconfig/network-instance/openconfig-network-instance.yang
  - ./yang-repo/openconfig/system/openconfig-system.yang

Imported modules were sourced from:
  - ./yang-repo
  - ./yang-repo/iana
  - ./yang-repo/ietf
  - ./yang-repo/mappings
  - ./yang-repo/mappings/openconfig
  - ./yang-repo/openconfig
  - ./yang-repo/openconfig/acl
  - ./yang-repo/openconfig/aft
  - ./yang-repo/openconfig/bfd
  - ./yang-repo/openconfig/bgp
  - ./yang-repo/openconfig/defined-sets
  - ./yang-repo/openconfig/extensions
  - ./yang-repo/openconfig/flex-algo
  - ./yang-repo/openconfig/gnsi
  - ./yang-repo/openconfig/gribi
  - ./yang-repo/openconfig/interfaces
  - ./yang-repo/openconfig/isis
  - ./yang-repo/openconfig/keychain
  - ./yang-repo/openconfig/lacp
  - ./yang-repo/openconfig/lldp
  - ./yang-repo/openconfig/local-routing
  - ./yang-repo/openconfig/mpls
  - ./yang-repo/openconfig/multicast
  - ./yang-repo/openconfig/network-instance
  - ./yang-repo/openconfig/optical-transport
  - ./yang-repo/openconfig/ospf
  - ./yang-repo/openconfig/p4rt
  - ./yang-repo/openconfig/pcep
  - ./yang-repo/openconfig/platform
  - ./yang-repo/openconfig/policy-forwarding
  - ./yang-repo/openconfig/policy
  - ./yang-repo/openconfig/qos
  - ./yang-repo/openconfig/rib
  - ./yang-repo/openconfig/sampling
  - ./yang-repo/openconfig/segment-routing
  - ./yang-repo/openconfig/stp
  - ./yang-repo/openconfig/system
  - ./yang-repo/openconfig/test
  - ./yang-repo/openconfig/types
  - ./yang-repo/openconfig/vlan
  - ./yang-repo/srl_nokia
  - ./yang-repo/srl_nokia/models
  - ./yang-repo/srl_nokia/models/acl
  - ./yang-repo/srl_nokia/models/bfd
  - ./yang-repo/srl_nokia/models/common
  - ./yang-repo/srl_nokia/models/ethcfm
  - ./yang-repo/srl_nokia/models/grpc
  - ./yang-repo/srl_nokia/models/interfaces
  - ./yang-repo/srl_nokia/models/ndk
  - ./yang-repo/srl_nokia/models/network-instance
  - ./yang-repo/srl_nokia/models/oam
  - ./yang-repo/srl_nokia/models/platform
  - ./yang-repo/srl_nokia/models/qos
  - ./yang-repo/srl_nokia/models/routing-policy
  - ./yang-repo/srl_nokia/models/service-activation-testhead
  - ./yang-repo/srl_nokia/models/stp
  - ./yang-repo/srl_nokia/models/subscriber-mgmt
  - ./yang-repo/srl_nokia/models/sync
  - ./yang-repo/srl_nokia/models/system
  - ./yang-repo/srl_nokia/models/transport-security
  - ./yang-repo/srl_nokia/models/tunnel
  - ./yang-repo/srl_nokia/models/twamp
*/
package openconfigbfd

import (
	"reflect"

	oc "github.com/LeBaoTai/SDN-RD/internal/oc"
	"github.com/openconfig/ygnmi/ygnmi"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygot/ytypes"
)

// Bfd_Interface_Peer_RemoteAuthenticationEnabledPath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/remote-authentication-enabled YANG schema element.
type Bfd_Interface_Peer_RemoteAuthenticationEnabledPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_RemoteAuthenticationEnabledPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/remote-authentication-enabled YANG schema element.
type Bfd_Interface_Peer_RemoteAuthenticationEnabledPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_RemoteAuthenticationEnabledPath) PathOriginName() string {
	return ""
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/remote-authentication-enabled"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-authentication-enabled"
func (n *Bfd_Interface_Peer_RemoteAuthenticationEnabledPath) State() ygnmi.SingletonQuery[bool] {
	return ygnmi.NewSingletonQuery[bool](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "remote-authentication-enabled"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (bool, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).RemoteAuthenticationEnabled
			if ret == nil {
				var zero bool
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/remote-authentication-enabled"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-authentication-enabled"
func (n *Bfd_Interface_Peer_RemoteAuthenticationEnabledPathAny) State() ygnmi.WildcardQuery[bool] {
	return ygnmi.NewWildcardQuery[bool](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "remote-authentication-enabled"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (bool, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).RemoteAuthenticationEnabled
			if ret == nil {
				var zero bool
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_Peer_RemoteControlPlaneIndependentPath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/remote-control-plane-independent YANG schema element.
type Bfd_Interface_Peer_RemoteControlPlaneIndependentPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_RemoteControlPlaneIndependentPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/remote-control-plane-independent YANG schema element.
type Bfd_Interface_Peer_RemoteControlPlaneIndependentPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_RemoteControlPlaneIndependentPath) PathOriginName() string {
	return ""
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/remote-control-plane-independent"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-control-plane-independent"
func (n *Bfd_Interface_Peer_RemoteControlPlaneIndependentPath) State() ygnmi.SingletonQuery[bool] {
	return ygnmi.NewSingletonQuery[bool](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "remote-control-plane-independent"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (bool, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).RemoteControlPlaneIndependent
			if ret == nil {
				var zero bool
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/remote-control-plane-independent"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-control-plane-independent"
func (n *Bfd_Interface_Peer_RemoteControlPlaneIndependentPathAny) State() ygnmi.WildcardQuery[bool] {
	return ygnmi.NewWildcardQuery[bool](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "remote-control-plane-independent"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (bool, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).RemoteControlPlaneIndependent
			if ret == nil {
				var zero bool
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_Peer_RemoteDiagnosticCodePath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/remote-diagnostic-code YANG schema element.
type Bfd_Interface_Peer_RemoteDiagnosticCodePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_RemoteDiagnosticCodePathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/remote-diagnostic-code YANG schema element.
type Bfd_Interface_Peer_RemoteDiagnosticCodePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_RemoteDiagnosticCodePath) PathOriginName() string {
	return ""
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/remote-diagnostic-code"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-diagnostic-code"
func (n *Bfd_Interface_Peer_RemoteDiagnosticCodePath) State() ygnmi.SingletonQuery[oc.E_OpenconfigBfd_BfdDiagnosticCode] {
	return ygnmi.NewSingletonQuery[oc.E_OpenconfigBfd_BfdDiagnosticCode](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "remote-diagnostic-code"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_OpenconfigBfd_BfdDiagnosticCode, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).RemoteDiagnosticCode
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/remote-diagnostic-code"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-diagnostic-code"
func (n *Bfd_Interface_Peer_RemoteDiagnosticCodePathAny) State() ygnmi.WildcardQuery[oc.E_OpenconfigBfd_BfdDiagnosticCode] {
	return ygnmi.NewWildcardQuery[oc.E_OpenconfigBfd_BfdDiagnosticCode](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "remote-diagnostic-code"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_OpenconfigBfd_BfdDiagnosticCode, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).RemoteDiagnosticCode
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_Peer_RemoteDiscriminatorPath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/remote-discriminator YANG schema element.
type Bfd_Interface_Peer_RemoteDiscriminatorPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_RemoteDiscriminatorPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/remote-discriminator YANG schema element.
type Bfd_Interface_Peer_RemoteDiscriminatorPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_RemoteDiscriminatorPath) PathOriginName() string {
	return ""
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/remote-discriminator"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-discriminator"
func (n *Bfd_Interface_Peer_RemoteDiscriminatorPath) State() ygnmi.SingletonQuery[string] {
	return ygnmi.NewSingletonQuery[string](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "remote-discriminator"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).RemoteDiscriminator
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/remote-discriminator"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-discriminator"
func (n *Bfd_Interface_Peer_RemoteDiscriminatorPathAny) State() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "remote-discriminator"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).RemoteDiscriminator
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_Peer_RemoteMinimumReceiveIntervalPath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/remote-minimum-receive-interval YANG schema element.
type Bfd_Interface_Peer_RemoteMinimumReceiveIntervalPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_RemoteMinimumReceiveIntervalPathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/remote-minimum-receive-interval YANG schema element.
type Bfd_Interface_Peer_RemoteMinimumReceiveIntervalPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_RemoteMinimumReceiveIntervalPath) PathOriginName() string {
	return ""
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/remote-minimum-receive-interval"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-minimum-receive-interval"
func (n *Bfd_Interface_Peer_RemoteMinimumReceiveIntervalPath) State() ygnmi.SingletonQuery[uint32] {
	return ygnmi.NewSingletonQuery[uint32](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "remote-minimum-receive-interval"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).RemoteMinimumReceiveInterval
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/remote-minimum-receive-interval"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-minimum-receive-interval"
func (n *Bfd_Interface_Peer_RemoteMinimumReceiveIntervalPathAny) State() ygnmi.WildcardQuery[uint32] {
	return ygnmi.NewWildcardQuery[uint32](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "remote-minimum-receive-interval"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (uint32, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).RemoteMinimumReceiveInterval
			if ret == nil {
				var zero uint32
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_Peer_RemoteSessionStatePath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/remote-session-state YANG schema element.
type Bfd_Interface_Peer_RemoteSessionStatePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_RemoteSessionStatePathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/remote-session-state YANG schema element.
type Bfd_Interface_Peer_RemoteSessionStatePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_RemoteSessionStatePath) PathOriginName() string {
	return ""
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/remote-session-state"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-session-state"
func (n *Bfd_Interface_Peer_RemoteSessionStatePath) State() ygnmi.SingletonQuery[oc.E_OpenconfigBfd_BfdSessionState] {
	return ygnmi.NewSingletonQuery[oc.E_OpenconfigBfd_BfdSessionState](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "remote-session-state"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_OpenconfigBfd_BfdSessionState, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).RemoteSessionState
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/remote-session-state"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/remote-session-state"
func (n *Bfd_Interface_Peer_RemoteSessionStatePathAny) State() ygnmi.WildcardQuery[oc.E_OpenconfigBfd_BfdSessionState] {
	return ygnmi.NewWildcardQuery[oc.E_OpenconfigBfd_BfdSessionState](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "remote-session-state"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_OpenconfigBfd_BfdSessionState, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).RemoteSessionState
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Bfd_Interface_Peer_SessionStatePath represents the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/session-state YANG schema element.
type Bfd_Interface_Peer_SessionStatePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// Bfd_Interface_Peer_SessionStatePathAny represents the wildcard version of the /openconfig-bfd/bfd/interfaces/interface/peers/peer/state/session-state YANG schema element.
type Bfd_Interface_Peer_SessionStatePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *Bfd_Interface_Peer_SessionStatePath) PathOriginName() string {
	return ""
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/session-state"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/session-state"
func (n *Bfd_Interface_Peer_SessionStatePath) State() ygnmi.SingletonQuery[oc.E_OpenconfigBfd_BfdSessionState] {
	return ygnmi.NewSingletonQuery[oc.E_OpenconfigBfd_BfdSessionState](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "session-state"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_OpenconfigBfd_BfdSessionState, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).SessionState
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
//
//	Defining module:      "openconfig-bfd"
//	Instantiating module: "openconfig-bfd"
//	Path from parent:     "state/session-state"
//	Path from root:       "/bfd/interfaces/interface/peers/peer/state/session-state"
func (n *Bfd_Interface_Peer_SessionStatePathAny) State() ygnmi.WildcardQuery[oc.E_OpenconfigBfd_BfdSessionState] {
	return ygnmi.NewWildcardQuery[oc.E_OpenconfigBfd_BfdSessionState](
		"Bfd_Interface_Peer",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "session-state"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (oc.E_OpenconfigBfd_BfdSessionState, bool) {
			ret := gs.(*oc.Bfd_Interface_Peer).SessionState
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.Bfd_Interface_Peer) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}
