/*
Package openconfigdefinedsets is a generated package which contains definitions
of structs which generate gNMI paths for a YANG schema.

This package was generated by ygnmi version: v0.15.0: (ygot: v0.35.0)
using the following YANG input files:
	- ./yang-repo/openconfig/interfaces/openconfig-interfaces.yang
	- ./yang-repo/openconfig/interfaces/openconfig-if-ip.yang
	- ./yang-repo/openconfig/bgp/openconfig-bgp.yang
	- ./yang-repo/openconfig/acl/openconfig-acl.yang
	- ./yang-repo/openconfig/network-instance/openconfig-network-instance.yang
	- ./yang-repo/openconfig/system/openconfig-system.yang
Imported modules were sourced from:
	- ./yang-repo
	- ./yang-repo/iana
	- ./yang-repo/ietf
	- ./yang-repo/mappings
	- ./yang-repo/mappings/openconfig
	- ./yang-repo/openconfig
	- ./yang-repo/openconfig/acl
	- ./yang-repo/openconfig/aft
	- ./yang-repo/openconfig/bfd
	- ./yang-repo/openconfig/bgp
	- ./yang-repo/openconfig/defined-sets
	- ./yang-repo/openconfig/extensions
	- ./yang-repo/openconfig/flex-algo
	- ./yang-repo/openconfig/gnsi
	- ./yang-repo/openconfig/gribi
	- ./yang-repo/openconfig/interfaces
	- ./yang-repo/openconfig/isis
	- ./yang-repo/openconfig/keychain
	- ./yang-repo/openconfig/lacp
	- ./yang-repo/openconfig/lldp
	- ./yang-repo/openconfig/local-routing
	- ./yang-repo/openconfig/mpls
	- ./yang-repo/openconfig/multicast
	- ./yang-repo/openconfig/network-instance
	- ./yang-repo/openconfig/optical-transport
	- ./yang-repo/openconfig/ospf
	- ./yang-repo/openconfig/p4rt
	- ./yang-repo/openconfig/pcep
	- ./yang-repo/openconfig/platform
	- ./yang-repo/openconfig/policy-forwarding
	- ./yang-repo/openconfig/policy
	- ./yang-repo/openconfig/qos
	- ./yang-repo/openconfig/rib
	- ./yang-repo/openconfig/sampling
	- ./yang-repo/openconfig/segment-routing
	- ./yang-repo/openconfig/stp
	- ./yang-repo/openconfig/system
	- ./yang-repo/openconfig/test
	- ./yang-repo/openconfig/types
	- ./yang-repo/openconfig/vlan
	- ./yang-repo/srl_nokia
	- ./yang-repo/srl_nokia/models
	- ./yang-repo/srl_nokia/models/acl
	- ./yang-repo/srl_nokia/models/bfd
	- ./yang-repo/srl_nokia/models/common
	- ./yang-repo/srl_nokia/models/ethcfm
	- ./yang-repo/srl_nokia/models/grpc
	- ./yang-repo/srl_nokia/models/interfaces
	- ./yang-repo/srl_nokia/models/ndk
	- ./yang-repo/srl_nokia/models/network-instance
	- ./yang-repo/srl_nokia/models/oam
	- ./yang-repo/srl_nokia/models/platform
	- ./yang-repo/srl_nokia/models/qos
	- ./yang-repo/srl_nokia/models/routing-policy
	- ./yang-repo/srl_nokia/models/service-activation-testhead
	- ./yang-repo/srl_nokia/models/stp
	- ./yang-repo/srl_nokia/models/subscriber-mgmt
	- ./yang-repo/srl_nokia/models/sync
	- ./yang-repo/srl_nokia/models/system
	- ./yang-repo/srl_nokia/models/transport-security
	- ./yang-repo/srl_nokia/models/tunnel
	- ./yang-repo/srl_nokia/models/twamp
*/
package openconfigdefinedsets

import (
	"reflect"
	oc "github.com/LeBaoTai/SDN-RD/internal/oc"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygnmi/ygnmi"
	"github.com/openconfig/ygot/ytypes"
)

// DefinedSets_PortSet_NamePath represents the /openconfig-defined-sets/defined-sets/port-sets/port-set/state/name YANG schema element.
type DefinedSets_PortSet_NamePath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// DefinedSets_PortSet_NamePathAny represents the wildcard version of the /openconfig-defined-sets/defined-sets/port-sets/port-set/state/name YANG schema element.
type DefinedSets_PortSet_NamePathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *DefinedSets_PortSet_NamePath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-defined-sets"
// 	Instantiating module: "openconfig-defined-sets"
// 	Path from parent:     "state/name"
// 	Path from root:       "/defined-sets/port-sets/port-set/state/name"
func (n *DefinedSets_PortSet_NamePath) State() ygnmi.SingletonQuery[string] {
	return ygnmi.NewSingletonQuery[string](
		"DefinedSets_PortSet",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "name"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.DefinedSets_PortSet).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.DefinedSets_PortSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-defined-sets"
// 	Instantiating module: "openconfig-defined-sets"
// 	Path from parent:     "state/name"
// 	Path from root:       "/defined-sets/port-sets/port-set/state/name"
func (n *DefinedSets_PortSet_NamePathAny) State() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"DefinedSets_PortSet",
		true,
		false,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "name"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.DefinedSets_PortSet).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.DefinedSets_PortSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-defined-sets"
// 	Instantiating module: "openconfig-defined-sets"
// 	Path from parent:     "config/name"
// 	Path from root:       "/defined-sets/port-sets/port-set/config/name"
func (n *DefinedSets_PortSet_NamePath) Config() ygnmi.ConfigQuery[string] {
	return ygnmi.NewConfigQuery[string](
		"DefinedSets_PortSet",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "name"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.DefinedSets_PortSet).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.DefinedSets_PortSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-defined-sets"
// 	Instantiating module: "openconfig-defined-sets"
// 	Path from parent:     "config/name"
// 	Path from root:       "/defined-sets/port-sets/port-set/config/name"
func (n *DefinedSets_PortSet_NamePathAny) Config() ygnmi.WildcardQuery[string] {
	return ygnmi.NewWildcardQuery[string](
		"DefinedSets_PortSet",
		false,
		true,
		true,
		true,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "name"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) (string, bool) { 
			ret := gs.(*oc.DefinedSets_PortSet).Name
			if ret == nil {
				var zero string
				return zero, false
			}
			return *ret, true
		},
		func() ygot.ValidatedGoStruct { return new(oc.DefinedSets_PortSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// DefinedSets_PortSet_PortPath represents the /openconfig-defined-sets/defined-sets/port-sets/port-set/state/port YANG schema element.
type DefinedSets_PortSet_PortPath struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// DefinedSets_PortSet_PortPathAny represents the wildcard version of the /openconfig-defined-sets/defined-sets/port-sets/port-set/state/port YANG schema element.
type DefinedSets_PortSet_PortPathAny struct {
	*ygnmi.NodePath
	parent ygnmi.PathStruct
}

// PathOrigin returns the name of the origin for the path object.
func (n *DefinedSets_PortSet_PortPath) PathOriginName() string {
     return ""
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-defined-sets"
// 	Instantiating module: "openconfig-defined-sets"
// 	Path from parent:     "state/port"
// 	Path from root:       "/defined-sets/port-sets/port-set/state/port"
func (n *DefinedSets_PortSet_PortPath) State() ygnmi.SingletonQuery[[]oc.DefinedSets_PortSet_Port_Union] {
	return ygnmi.NewSingletonQuery[[]oc.DefinedSets_PortSet_Port_Union](
		"DefinedSets_PortSet",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "port"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.DefinedSets_PortSet_Port_Union, bool) { 
			ret := gs.(*oc.DefinedSets_PortSet).Port
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.DefinedSets_PortSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// State returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-defined-sets"
// 	Instantiating module: "openconfig-defined-sets"
// 	Path from parent:     "state/port"
// 	Path from root:       "/defined-sets/port-sets/port-set/state/port"
func (n *DefinedSets_PortSet_PortPathAny) State() ygnmi.WildcardQuery[[]oc.DefinedSets_PortSet_Port_Union] {
	return ygnmi.NewWildcardQuery[[]oc.DefinedSets_PortSet_Port_Union](
		"DefinedSets_PortSet",
		true,
		false,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"state", "port"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.DefinedSets_PortSet_Port_Union, bool) { 
			ret := gs.(*oc.DefinedSets_PortSet).Port
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.DefinedSets_PortSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-defined-sets"
// 	Instantiating module: "openconfig-defined-sets"
// 	Path from parent:     "config/port"
// 	Path from root:       "/defined-sets/port-sets/port-set/config/port"
func (n *DefinedSets_PortSet_PortPath) Config() ygnmi.ConfigQuery[[]oc.DefinedSets_PortSet_Port_Union] {
	return ygnmi.NewConfigQuery[[]oc.DefinedSets_PortSet_Port_Union](
		"DefinedSets_PortSet",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "port"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.DefinedSets_PortSet_Port_Union, bool) { 
			ret := gs.(*oc.DefinedSets_PortSet).Port
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.DefinedSets_PortSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}

// Config returns a Query that can be used in gNMI operations.
// 	Defining module:      "openconfig-defined-sets"
// 	Instantiating module: "openconfig-defined-sets"
// 	Path from parent:     "config/port"
// 	Path from root:       "/defined-sets/port-sets/port-set/config/port"
func (n *DefinedSets_PortSet_PortPathAny) Config() ygnmi.WildcardQuery[[]oc.DefinedSets_PortSet_Port_Union] {
	return ygnmi.NewWildcardQuery[[]oc.DefinedSets_PortSet_Port_Union](
		"DefinedSets_PortSet",
		false,
		true,
		true,
		false,
		true,
		false,
		ygnmi.NewNodePath(
			[]string{"config", "port"},
			nil,
			n.parent,
		),
		func(gs ygot.ValidatedGoStruct) ([]oc.DefinedSets_PortSet_Port_Union, bool) { 
			ret := gs.(*oc.DefinedSets_PortSet).Port
			v := reflect.ValueOf(ret)
			return ret, v.IsValid() && !v.IsZero()
		},
		func() ygot.ValidatedGoStruct { return new(oc.DefinedSets_PortSet) },
		func() *ytypes.Schema {
			return &ytypes.Schema{
				Root:       &oc.Root{},
				SchemaTree: oc.SchemaTree,
				Unmarshal:  oc.Unmarshal,
			}
		},
		nil,
		nil,
	)
}
